<div class="step-block">
    <form name="<?php echo $this->paymentForm->getName(); ?>" method="<?php echo $this->paymentForm->getMethod(); ?>" id="createOrderForm">
        <dl class="zend_form">
            <?php echo $this->paymentForm->getElement('paymentType')->render(); ?>
        </dl>
    </form>
</div>

<?php
$this->gaEvent = ['category' => 'Замовлення', 'action' => 'Оплата', 'label' => 'Крок-1'];
echo $this->render('controls/ga/event.phtml');
?>
