<?php if (count($this->basketItems) > 0): ?>
    <form method="POST" action="<?php echo $this->baseUrl; ?>/<?php echo $this->language; ?>/user/create-order" class="grid-100">
        <input type="hidden" name="currentForm" value="Busket" id="currentForm">
        <table class="tablesorter" cellpadding="3" cellspacing="1">
            <thead>
            <tr>
                <th><?php echo $this->t->_('tov_type'); ?></th>
                <th width="80px;"><?php echo $this->t->_('tov_status'); ?></th>
                <th width="70px;"><?php echo $this->t->_('syma'); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php $i = 1; ?>
            <?php $orderId = 0; ?>
            <?php foreach ($this->basketItems as $key => $value): ?>
                <?php if ($orderId != $value['order_id']): ?>
                    <?php $orderId = $value['order_id']; ?>
                    <tr class="o_<?php echo $value['order_id']; ?>">
                        <td colspan="7">
                            <div style="width: auto; overflow: auto; font-size: 13px;">
                                <div style="float: left;">
                                    <div class="orderStatus" style="padding-bottom: 5px;">
                                        <div>
                                            <?php echo $this->t->_('order_number'); ?>
                                            : <span class="orderId"><?php echo $value['order_id']; ?></span>
                                        </div>
                                        <div>
                                            <?php echo $this->t->_('order_date') . ': ' . date('d/m/Y H:i:s', strtotime($value['date'])); ?>
                                        </div>
                                        <?php echo $this->t->_('order_status'); ?>:
                                        <span class="currentOrderStatus">
                                            <?php echo $this->t->_($value['order_status']); ?>
                                        </span>
                                        <select class="changeOrderStatus hidden">
                                            <option value="created"<?php if ($value['order_status'] == 'created'): ?> selected="selected"<?php endif; ?>>
                                                <?php echo $this->t->_("created"); ?>
                                            </option>
                                            <option value="inOrder"<?php if ($value['order_status'] == 'inOrder'): ?> selected="selected"<?php endif; ?>>
                                                <?php echo $this->t->_("inOrder"); ?>
                                            </option>
                                            <option value="produced"<?php if ($value['order_status'] == 'produced'): ?> selected="selected"<?php endif; ?>>
                                                <?php echo $this->t->_("produced"); ?>
                                            </option>
                                            <option value="sended"<?php if ($value['order_status'] == 'sended'): ?> selected="selected"<?php endif; ?>>
                                                <?php echo $this->t->_("sended"); ?>
                                            </option>
                                            <option value="closed"<?php if ($value['order_status'] == 'closed'): ?> selected="selected"<?php endif; ?>>
                                                <?php echo $this->t->_("closed"); ?>
                                            </option>
                                            <option value="canceled"<?php if ($value['order_status'] == 'canceled'): ?> selected="selected"<?php endif; ?>>
                                                <?php echo $this->t->_("canceled"); ?>
                                            </option>
                                            <option value="canceled"<?php if ($value['order_status'] == 'duplicate'): ?> selected="selected"<?php endif; ?>>
                                                <?php echo $this->t->_("duplicate"); ?>
                                            </option>
                                            <option value="canceled"<?php if ($value['order_status'] == 'test'): ?> selected="selected"<?php endif; ?>>
                                                <?php echo $this->t->_("test"); ?>
                                            </option>
                                        </select>
                                        <span>
                                            <img class="editOrderStatusBtn" style="cursor:pointer;" src="<?php echo $this->baseUrl ?>/public/theme/user/table/edit.png" />
                                            <img class="saveOrderStatusBtn" style="display: none; cursor:pointer; padding-top:3px" src="<?php echo $this->baseUrl ?>/public/theme/user/table/save.png" />
                                        </span>
                                        <div>
                                            <?php echo $this->t->_('payment_type'); ?>
                                            : <span class="orderId"><?php echo $this->t->_($value['payment_sys']); ?></span>
                                        </div>
                                        <div>
                                            <?php echo $this->t->_('dostavka'); ?>
                                            : <span class="orderId"><?php echo $this->t->_($value['dostavka_else']); ?></span>
                                        </div>
                                        <?php if ($value['dostavka_lustivok']): ?>
                                            <div>
                                                <?php echo $this->t->_('dostavka_lustivok'); ?>
                                                : <span class="orderId"><?php echo $this->t->_($value['dostavka_lustivok']); ?></span>
                                            </div>
                                        <?php endif; ?>
                                        <div>
                                            <?php echo $this->t->_('payment'); ?>
                                            : <span class="orderId"><?php echo $value['order_payment']; ?></span> <?php echo $this->t->_('grn'); ?>
                                            .
                                        </div>
                                    </div>
                                </div>
                                <div style="float: right; width: 250px; border: 1px solid #E7E7E7; padding: 3px;">
                                    <div>
                                        <?php echo $this->t->_('user_name'); ?>
                                        : <span class="orderId"><?php echo $value['user_name']; ?></span>
                                    </div>
                                    <div>
                                        <?php echo $this->t->_('phone'); ?>
                                        : <span class="orderId"><?php echo $value['phone']; ?></span>
                                    </div>
                                    <div>
                                        <?php echo $this->t->_('email'); ?>
                                        : <span class="orderId"><?php echo $value['email']; ?></span>
                                    </div>
                                    <div>
                                        <?php echo $this->t->_('adresat'); ?>: <?php echo $value['address']; ?>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                <?php endif; ?>

                <tr align="center" class="o_<?php echo $value['order_id']; ?>">
                    <td>
                        <?php if ($value['product_group'] == 'postcard'): ?>
                            <a href="<?= $this->h()->url()->build("/admin/{$value['product_group']}/id/{$value['id']}"); ?>" target="_blank">
                                <?php echo $this->t->_($value['product_group']); ?>
                            </a>
                        <?php else: ?>
                            <a href="<?= $this->h()->url()->build("/produces/reviewitem/id/{$value['id']}"); ?>" class="mbox">
                                <?php echo $this->t->_($this->h()->basket()->showItemName($value['dataXml'])); ?>
                            </a>
                        <?php endif; ?>
                        <?php $this->h()->basket()->showDeteils($this->t, $value['dataXml']); ?>
                    </td>
                    <td style="display: none;">
                        <span class="currentStatus">
                            <?php echo $this->t->_($value['status']); ?>
                        </span>
                        <?php if (($value['status'] == 'inOrder') || ($value['status'] == 'produced')): ?>
                            <select class="changeStatus" style="display: none;">
                                <option value="inOrder"<?php if ($value['status'] == 'inOrder'): ?> selected="selected"<?php endif; ?>>
                                    <?php echo $this->t->_("inOrder"); ?>
                                </option>
                                <option value="produced"<?php if ($value['status'] == 'produced'): ?> selected="selected"<?php endif; ?>>
                                    <?php echo $this->t->_("produced"); ?>
                                </option>
                            </select>
                            <div style="float:right;">
                                <img class="editStatusBtn" style="cursor:pointer;" src="<?php echo $this->baseUrl ?>/public/theme/user/table/edit.png" />
                                <img class="saveStatusBtn" style="display: none; cursor:pointer; padding-top:3px" src="<?php echo $this->baseUrl ?>/public/theme/user/table/save.png" />
                            </div>
                        <?php endif; ?>
                    </td>
                    <td><?php echo $value['count']; ?></td>
                    <td>
                        <span class="priceItems">
                            <?php if ($value['item_payment']): ?>
                                <?php echo $value['item_payment']; ?>
                            <?php else: ?>
                                <?php echo $value['count'] * $this->h()->basket()->showPrice($value['dataXml']); ?>
                            <?php endif; ?>
                        </span>
                        <?php echo $this->t->_('grn'); ?>.
                    </td>
                </tr>
                <?php $i++; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </form>
<?php else: ?>
    <div class="grid-100" align="center" style="padding-top:70px;">
        <?php echo $this->t->_('no_new_orders'); ?>
    </div>
<?php endif; ?>
