<?php if ($this->tracking): ?>
    <script type="text/javascript">
        $(document).ready(function(){
            ga('require', 'ecommerce');
            ga('ecommerce:addTransaction', {
                id: '<?= $this->order->id ?>',
                revenue: '<?= number_format($this->order->payment, 2, '.', '') ?>',
                currency: 'UAH'
            });

            <?php foreach($this->orderedItems as $orderedItem): ?>
                ga('ecommerce:addItem', {
                    id: '<?= $this->order->id ?>',
                    sku: '<?= $orderedItem['id'] ?>',
                    name: '<?= $this->t->_($orderedItem['name']) ?>',
                    price: '<?= number_format($orderedItem['price']/$orderedItem['count'], 2, '.', '') ?>',
                    currency: 'UAH',
                    quantity: '<?= $orderedItem['count'] ?>'
                });
            <?php endforeach ?>

            ga('ecommerce:send');
        });
    </script>
<?php endif ?>
