<?php $imgAlt = $this->t->_($this->item) . '. ' . $this->productName; ?>

<div class="cup">
    <?php if ($this->itemXml->template == '4'): ?>
        <div class="long">
            <div class="head"></div>
            <div class="content">
                <span class="border"></span>
                <?php $this->h()->image()->getSmallInBoxImgPreview(2.95652, $this->itemXml, 'main', $imgAlt, 0, 0) ?>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($this->itemXml->template == '5'): ?>
        <div class="double left">
            <div class="content">
                <div class="image size">
                    <?php $this->h()->image()->getSmallInBoxImgPreview(1.56296, $this->itemXml, 'left', $imgAlt, 0, 0); ?>
                </div>
            </div>
        </div>
        <div class="double right">
            <div class="content">
                <div class="image size">
                    <?php $this->h()->image()->getSmallInBoxImgPreview(1.56296, $this->itemXml, 'right', $imgAlt, 0, 0); ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>
