<?= $this->render('controls/header.phtml'); ?>

<div class="grid-container">
    <div class="breadcrumbs grid-100" itemprop="breadcrumb">
        <a href="<?= $this->h()->url()->build(''); ?>"><?= $this->t->_('main_page_link'); ?></a> &raquo;
        <?= $this->t->_('confirm_email'); ?>
        <div class="underline"></div>
    </div>
    <div class="grid-100">
        <div class="center-allign">
            <h1>
                <?= ($this->emailIsConfirmed) ? $this->t->_('your_emails_is_confirmed') : $this->t->_('incorrect_url'); ?>
            </h1>
            <img src="<?php $this->h()->static()->path('mail/confirmation.png'); ?>">
        </div>
    </div>
</div>

<?= $this->render('controls/footer.phtml'); ?>
