<?php echo $this->render('controls/header.phtml'); ?>

<script type="text/javascript">
    $(document).ready(function(){
        setTimeout(function() { document.location.href = baseUrl }, 5000);
    });
</script>
<div class="grid-container">
    <div class="grid-100 notification-msg center-allign">
        <span><?php echo $this->t->_('congratulation'); ?></span>
    </div>
</div>

<?php echo $this->render('controls/footer.phtml'); ?>
