<?php echo $this->render('controls/header.phtml'); ?>

<script type="text/javascript" language="javascript">
    var bad_captcha = '<?php echo $this->t->_('bad_captcha'); ?>'
    var is_empty = '<?php echo $this->t->_('is_empty'); ?>'
    var too_short = '<?php echo str_replace('%min%', 3, $this->t->_('too_short')); ?>'
    var too_long = '<?php echo str_replace('%max%', 50, $this->t->_('too_long')); ?>'
    var not_same = '<?php echo $this->t->_('not_same'); ?>'
    var not_match = '<?php echo $this->t->_('not_match'); ?>'
    var invalid = '<?php echo $this->t->_('invalid'); ?>'
    var invalid_hostname = '<?php echo $this->t->_('invalid_hostname'); ?>'
    var invalid_mx_record = '<?php echo $this->t->_('invalid_mx_record'); ?>'
    var dot_atom = '<?php echo $this->t->_('dot_atom'); ?>'
    var quoted_string = '<?php echo $this->t->_('quoted_string'); ?>'
    var invalid_local_part = '<?php echo $this->t->_('invalid_local_part'); ?>'
</script>
<div class="grid-container">
    <div class="breadcrumbs grid-100" itemprop="breadcrumb">
        <a href="<?= $this->h()->url()->build(''); ?>"><?php echo $this->t->_('main_page_link'); ?></a> &raquo;
        <?php echo $this->t->_('registration_form'); ?>
        <div class="underline"></div>
    </div>
    <div class="grid-100">
        <?php echo $this->form ?>
    </div>
</div>

<?php echo $this->render('controls/footer.phtml'); ?>
