<?php echo $this->render('controls/header.phtml'); ?>

<div class="grid-container">
    <div class="breadcrumbs grid-100" itemprop="breadcrumb">
        <a href="<?= $this->h()->url()->build('/'); ?>"><?php echo $this->t->_('main_page_link'); ?></a> &raquo;
        <?php echo $this->t->_('resend_password'); ?>
        <div class="underline"></div>
    </div>

    <div class="grid-100">
        <?php if($this->allowReset): ?>
            <?php if($this->passwodr_is_resetet): ?>
                <div class="center-allign">
                    <?php //TODO: fix url ?>
                    <?php echo sprintf($this->t->_('passwodr_is_resetet'),
                     '<a href="' .  $this->h()->url()->build('/user/login-wnd') .'" class="mbox">' .
                            $this->t->_('come_in') .
                     '</a>'); ?>
                </div>
            <?php else: ?>
                <?php echo $this->reset_pass_form; ?>
            <?php endif; ?>
        <?php else: ?>
            <div class="notification-msg center-allign">
                <span><?php echo $this->t->_('incorrect_url'); ?></span>
            </div>
        <?php endif; ?>
    </div>
</div>
<?php echo $this->render('controls/footer.phtml'); ?>
