<div id="popup-wnd-data-content" class="popup-wnd-admin-edit-product-size">
    <?php echo $this->render('controls/emptyheader.phtml'); ?>
    <style>
        .zend_form dd{
            line-height: 18px;
            margin: 3px 2px 3px 0px;
        }
        #tshirt-color{
            padding: 0;
            margin: 0;
            height: 34px;
        }
    </style>

    <script>
        $(document).ready(function(){
            $('.remove-theme-btn').click(function() {
                var allowedTShirtColors = '';
                $('#allowed-tshirt-color span').each(function(index) {
                    if($(this).hasClass('selected')) {
                        allowedTShirtColors += (allowedTShirtColors != '') ? ',' + $(this).data('color') : $(this).data('color');
                    }
                });
                $.ajax({
                    type: "POST",
                    url: baseUrl + "/admin/edit-product",
                    data: {
                        id: '<?php echo $this->product['id']; ?>',
                        status: $('input:radio[name=status]:checked').val(),
                        themeId: $("#new-theme-id").attr("data-selected-items"),
                        tagId: $("#new-tag-id").attr("data-selected-items"),
                        color: $('#tshirt-color span.selected').attr('data-color'),
                        allowedColors: allowedTShirtColors,
                        costDiff: $('#cost-diff').val(),
                        ua: $('#ua').val(),
                        ru: $('#ru').val(),
                        title_ua: $('#title-ua').val(),
                        title_ru: $('#title-ru').val(),
                        description_ua: $('#description-ua').val(),
                        description_ru: $('#description-ru').val(),
                        header_ua: $('#header-ua').val(),
                        header_ru: $('#header-ru').val(),
                        text_ua: $('#text-ua').val(),
                        text_ru: $('#text-ru').val()
                    },
                    success: function(data) {
                        mboxRemove();
                    }
                });
            });
            $('#new-theme-id').tokenize({newElements: false});
            $('#new-tag-id').tokenize({newElements: false});
            $('#tshirt-color span').click(function(){
                $('#tshirt-color span').removeClass('selected');
                $(this).addClass('selected');
            });
            $('#allowed-tshirt-color span').click(function(){
                if ($(this).hasClass('selected')) {
                    $(this).removeClass('selected');
                } else {
                    $(this).addClass('selected');
                }
            });
        });
    </script>
    <div>
        <div class="popup-wnd-header"><?php echo $this->t->_('edit_product'); ?></div>
        <div>
            <dl class="zend_form">
                <dt><label><?php echo $this->t->_('theme'); ?>:</label></dt>
                <dd>
                    <select id="new-theme-id" multiple="multiple">
                        <?php foreach ($this->productsThemes as $theme): ?>
                            <option value="<?php echo $theme['id']; ?>" <?php if(in_array($theme['id'], $this->product['itemThemeIds'], true)): ?> selected="selected"<?php endif; ?>>
                                <?php echo $theme[$this->language]; ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </dd>

                <dt><label><?php echo $this->t->_('tag'); ?>:</label></dt>
                <dd>
                    <select id="new-tag-id" multiple="multiple">
                        <?php foreach ($this->productsTags as $tag): ?>
                            <option value="<?php echo $tag['id']; ?>" <?php if(in_array($tag['id'], $this->product['itemTagIds'], true)): ?> selected="selected"<?php endif; ?>>
                                <?php echo $tag[$this->language]; ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </dd>

                <dt><label><?php echo $this->t->_('status'); ?>:</label></dt>
                <dd style="padding-top: 6px;">
                    <?php $productStatuses = ['new', 'public', 'decline']; ?>
                    <?php foreach($productStatuses as $status): ?>
                        <?php $checked = ($this->product['status'] == $status) ? 'checked' : ''; ?>
                        <input type="radio" name="status" value="<?php echo $status; ?>"<?php echo $checked; ?>>
                        <span class="inline-radio"><?php echo $this->t->_($status); ?></span>
                    <?php endforeach; ?>
                </dd>

                <dt><label><?php echo $this->t->_('color'); ?>:</label></dt>
                <dd>
                    <?php if ($this->colors && is_array($this->colors) && count($this->colors)): ?>
                        <div id="tshirt-color">
                            <?php foreach ($this->colors as $color): ?>
                                <?php $selected = ($color == $this->product['color']) ? ' selected' : ''; ?>
                                <span class="<?php echo $color . $selected; ?>" data-color="<?php echo $color ?>"></span>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                </dd>

                <dt><label><?php echo $this->t->_('allowed_color'); ?>:</label></dt>
                <dd>
                    <?php if ($this->colors && is_array($this->colors) && count($this->colors)): ?>
                        <div id="allowed-tshirt-color">
                            <?php foreach ($this->colors as $color): ?>
                                <?php $selected = (false !== strpos($this->product['allowed_colors'], $color)) ? ' selected' : ''; ?>
                                <span class="<?php echo $color . $selected; ?>" data-color="<?php echo $color ?>"></span>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                </dd>

                <dt><label class="required" for="cost-diff"><?php echo $this->t->_('cost_diff'); ?>:</label></dt>
                <dd><input type="text" value="<?php echo $this->product['cost_diff']; ?>" id="cost-diff" name="cost-diff" style="width: 50px;"></dd>

                <dt><label class="required" for="ua"><?php echo $this->t->_('ua'); ?>:</label></dt>
                <dd><input type="text" value="<?php echo $this->product['ua']; ?>" id="ua" name="ua" style="width: 330px;"></dd>
                <dt><label class="required" for="ru"><?php echo $this->t->_('ru'); ?>:</label></dt>
                <dd><input type="text" value="<?php echo $this->product['ru']; ?>" id="ru" name="ru" style="width: 330px;"></dd>

                <dt><label class="required" for="title-ua"><?php echo $this->t->_('title_ua'); ?>:</label></dt>
                <dd><input type="text" value="<?php echo $this->product['title_ua']; ?>" id="title-ua" name="title-ua" style="width: 330px;"></dd>
                <dt><label class="required" for="title-ru"><?php echo $this->t->_('title_ru'); ?>:</label></dt>
                <dd><input type="text" value="<?php echo $this->product['title_ru']; ?>" id="title-ru" name="title-ru" style="width: 330px;"></dd>

                <dt><label class="required" for="description-ua"><?php echo $this->t->_('description_ua'); ?>:</label></dt>
                <dd><input type="text" value="<?php echo $this->product['description_ua'] ?>" id="description-ua" name="description-ua" style="width: 330px;"></dd>
                <dt><label class="required" for="description-ru"><?php echo $this->t->_('description_ru'); ?>:</label></dt>
                <dd><input type="text" value="<?php echo $this->product['description_ru'] ?>" id="description-ru" name="description-ru" style="width: 330px;"></dd>

                <dt><label for="header-ua"><?php echo $this->t->_('header_ua') ?>:</label></dt>
                <dd><input type="text" value="<?php echo $this->product['header_ua'] ?>" id="header-ua" name="header-ua" style="width: 330px;"></dd>
                <dt><label for="header-ru"><?php echo $this->t->_('header_ru') ?>:</label></dt>
                <dd><input type="text" value="<?php echo $this->product['header_ru'] ?>" id="header-ru" name="header-ru" style="width: 330px;"></dd>

                <dt><label for="text-ua"><?php echo $this->t->_('text_ua') ?>:</label></dt>
                <dd><textarea cols="30" rows="2" id="text-ua" name="text-ua"><?php echo $this->product['text_ua'] ?></textarea></dd>
                <dt><label for="text-ru"><?php echo $this->t->_('text_ru') ?>:</label></dt>
                <dd><textarea cols="30popup-wnd-admin-edit-product-size
                " rows="2" id="text-ru" name="text-ru"><?php echo $this->product['text_ru'] ?></textarea></dd>
            </dl>
        </div>
        <div class="popup-wnd-functional">
            <input class="remove-theme-btn" type="button" value="<?php echo $this->t->_('save'); ?>">
            <input class="close-popup-wnd" type="button" value="<?php echo $this->t->_('cancel'); ?>">
        </div>
    </div>

    <?php echo $this->render('controls/emptyfooter.phtml'); ?>
</div>
