<?php echo $this->render('controls/header.phtml'); ?>

<div class="grid-container">
    <div class="grid-100 mobile-grid-100" style="padding-bottom: 8px; text-align: right;">
        <a href="<?= $this->h()->url()->build("/admin/orders-history") ?>">
            <?php echo $this->t->_('orders_history'); ?>
        </a>
    </div>
    <?php echo $this->render('admin/controls/orders-table.phtml'); ?>
</div>

<?php echo $this->render('controls/footer.phtml'); ?>
