<?php echo $this->render('controls/header.phtml'); ?>

<script>
    $(document).ready(function(){
        $('.pay-out-btn').click(function() {
            $.ajax({
                type: "POST",
                url: baseUrl + "/admin/confirmpayout",
                data: {
                    id: $(this).attr('data-pay-out-id')
                },
                success: function(data) { }
            });
        });
    });
</script>


<div class="grid-container">
    <div class="grid-100">
    <?php if(count($this->payout)): ?>
        <table class="tablesorter" cellpadding="3" cellspacing="1">
            <thead>
                <tr>
                    <th><?php echo $this->t->_('created'); ?></th>
                    <th><?php echo $this->t->_('status'); ?></th>
                    <th><?php echo $this->t->_('user'); ?></th>
                    <th><?php echo $this->t->_('card_info'); ?></th>
                    <th><?php echo $this->t->_('syma'); ?></th>
                    <th style="width: 70px"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->payout as $kay => $value): ?>
                    <tr style="vertical-align: top;">
                        <td><?php echo $value['created']; ?></td>
                        <td><?php echo $value['status']; ?></td>
                        <td>
                            <?php echo $value['user_name']; ?><br/>
                            <?php echo $value['phone']; ?><br/>
                            <?php echo $value['email']; ?>
                        </td>
                        <td>
                            <?php echo $value['card_number']; ?><br/>
                            <?php echo $value['card_owner']; ?>
                        </td>
                        <td><?php echo $value['sum']; ?></td>
                        <td>
                            <input type="button" class="pay-out-btn" data-pay-out-id="<?php echo $value['id']; ?>" value="<?php echo $this->t->_('pay_out'); ?>">
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <div style="padding-top: 50px; text-align: center;">
            <?php echo $this->t->_('you_dont_have_new_payouts'); ?>
        </div>
    <?php endif; ?>
    </div>
</div>

<?php echo $this->render('controls/footer.phtml'); ?>
