<?php echo $this->render('controls/header.phtml'); ?>
<style>
    label {
        display: inline-block;
        width: 150px;
    }
</style>
<div class="grid-container">
    <div class="grid-100 mobile-grid-100">
        <div>
            <label><?php echo $this->t->_('user_name'); ?></label>
            <?= $this->user->user_name ?>
        </div>
        <div>
            <label><?php echo $this->t->_('email'); ?></label>
            <?= $this->user->email ?>
        </div>
        <div>
            <label><?php echo $this->t->_('phone'); ?></label>
            <?= $this->user->phone ?>
        </div>
    </div>
</div>
<?php echo $this->render('controls/footer.phtml'); ?>
