<div id="popup-wnd-data-content" class="popup-wnd-dialog-size">
    <?php echo $this->render('controls/emptyheader.phtml'); ?>

    <script>
        $(document).ready(function(){
            var idListForDelete = "";
            var chImgName = $("#userImages").find(".chImgName:checked").each(function(){
                var elId = ($(this).attr("id").split("_"))[1];
                idListForDelete += (idListForDelete != "") ? ";"+elId : elId;
            });

            if(idListForDelete != "") {
                $('.popup-wnd-warn-msg').html('<?php echo $this->t->_('do_you_realy_wont_to_delete_this_albums')?>?');
                $('#delete-albom-btn').css({'visibility': 'visible'});
                $('.remove-album-btn').click(function(){
                    $.ajax({
                        type: "POST",
                        url: baseUrl + "/user/deletealbums",
                        data: {
                            listId: idListForDelete
                        },
                        success: function(data) {
                            $("#userImages").load(
                                baseUrl + "/user/albums?v=" + baseVersion,
                                function(){ reloadBox(); mboxRemove();}
                            );
                        }
                    });
                    return false;
                });
            } else {
                $('.popup-wnd-warn-msg').html('<?php echo $this->t->_('you_didnt_select_albums_for_delete')?>.');
                $('#delete-albom-btn').hide();
                $('#delete-albom-close-btn').show();
            }
        });
    </script>

    <div id="popup-wnd-delete-theme">
        <div class="popup-wnd-header"><?php echo $this->t->_('delete_albums'); ?></div>
        <div class="popup-wnd-warn-msg"></div>
        <div class="popup-wnd-functional">
            <div id="delete-albom-btn" style="visibility: hidden;">
                <input class="remove-album-btn" type="button" value="<?php echo $this->t->_('yes'); ?>">
                <input class="close-popup-wnd" type="button" value="<?php echo $this->t->_('no'); ?>">
            </div>
            <div id="delete-albom-close-btn" style="display: none;">
                <input class="close-popup-wnd" type="button" value="<?php echo $this->t->_('close'); ?>">
            </div>
        </div>
    </div>

    <?php echo $this->render('controls/emptyfooter.phtml'); ?>
</div>