# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

    # web server
    config.vm.define :web do |web|
        web.vm.box = "ubuntu-14.04"
        # Debian Squeeze amd64 (Chef 10.24.4, Puppet 3.1.1, VirtualBox 4.2.12)
        web.vm.box_url = "~/vagran-box-ubuntu-server-14-04-chef.box"

        # Boot with a GUI so you can see the screen. (Default is headless)
        # config.vm.boot_mode = :gui
        web.vm.network :hostonly, "192.168.56.11"
        web.vm.network :bridged, :bridge => "en0"
        web.vm.forward_port 80, 8082
        web.vm.forward_port 9200, 9202

        web.vm.share_folder "www", "/var/www", "share", :create => true

        # web.vm.provision :shell, :inline => "sudo apt-get update"

        web.vm.provision :chef_solo do |chef|
            # chef.log_level = :debug
            chef.cookbooks_path = [
                "recipes/berks_cookbooks",
                "recipes/local_cookbooks"
            ]

            chef.add_recipe "locale"
            # chef.add_recipe "apt"
            # chef.add_recipe "vim"


            # chef.add_recipe "php7.0"

            # chef.add_recipe "imagemagick"

            chef.add_recipe "nginx"
            # chef.add_recipe "nginx_config"

            # chef.add_recipe "mysql_server"
            # chef.add_recipe "mysql_tuning"

            chef.add_recipe "java"
            chef.add_recipe "elasticsearch"
            chef.add_recipe "kibana::kibana3"
            chef.add_recipe "kibana::nginx"

            chef.json = {
                :localegen  => {
                    :lang => ["en_US", "en_US.utf8", "de_DE", "de_DE.utf8"]
                },
                :php => {
                    :version => "7.0.*"
                },
                :mysql => {
                    :server_root_password => "1"
                },
                :nginx_config => {
                    :hosts => [
                        {
                            :server_name => "photoprint",
                            :environment => "development"
                        }
                    ]
                },
                :java => {
                    :install_flavor => "oracle",
                    :jdk_version => "7",
                    :oracle => {
                        "accept_oracle_download_terms" => true
                    }
                },
                :elasticsearch => {
                    'node.name' => "photoprint-test"
                },
                :kibana => {
                    :version => "3",
                    :nginx => {
                        "server_name" => "kibana.photoprint"
                    }
                }
            }
        end
    end
end