---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    provider: vmware_fusion
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_ubuntu-12.04_chef-provisionerless.box
    require_chef_omnibus: true
- name: centos-6.5
  driver_config:
    provider: vmware_fusion
    box: opscode-centos-6.5
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_centos-6.5_chef-provisionerless.box
    require_chef_omnibus: true

suites:
- name: default
  run_list: ["recipe[apt]", "recipe[beaver]"]
  attributes: {}

- name: virtualenv
  run_list: ["recipe[apt]", "recipe[beaver]"]
  attributes:
    beaver:
      use_virtualenv: true

- name: keypair
  run_list: ["recipe[apt]", "recipe[python]","recipe[beaver]"]
  attributes:
    beaver:
      generate_keypair: true

- name: configuration
  run_list: ["recipe[apt]", "recipe[python]","recipe[beaver]"]
  attributes:
    beaver:
      configuration:
        ssh_options: 'StrictHostKeyChecking=no'
        ssh_tunnel: 'logging@logs.example.net'
        ssh_remote_host: 'localhost'
        ssh_remote_port: 6379
        ssh_tunnel_port: 6379
        redis_url: redis://localhost:6379/0
