name             'dev-box'
maintainer       'Mykhailo Kokolius'
maintainer_email 'mickokolius@gmail.com'
license          'All rights reserved'
description      'dev box'
version          '0.0.2'

depends 'locale', '~> 2.0.1'
depends 'vim', '~> 2.0.2'
depends 'curl', '~> 2.0.3'

depends 'nginx', '~> 2.7.6'
depends 'mysql', '~> 8.3.1'
depends 'redis', '~> 3.0.4'
depends 'imagemagick', '~> 0.2.3'
depends 'java', '~> 1.48.0'
depends 'selenium_grid', '~> 2.0.0'

depends 'postfix', '~> 5.0.1'
depends 'phpmyadmin', '~> 1.0.8'
