name             'devBox'
maintainer       'Mykhailo Kokolius'
maintainer_email 'mickokolius@gmail.com'
license          'All rights reserved'
description      'dev box'
version          '0.0.1'

depends 'locale', '~> 1.0.2'
depends 'apt', '~> 2.9.2'
depends 'vim', '~> 2.0.1'
depends 'curl', '~> 2.0.1'

depends 'nginx', '~> 2.7.6'
depends 'mysql', '~> 6.1.2'
depends 'mysql_tuning', '~> 0.4.0'
depends 'imagemagick', '~> 0.2.3'
depends 'java', '~> 1.39.0'
depends 'elasticsearch', '~> 2.2.1'
depends 'logstash', '~> 0.12.0'
depends 'postfix', '~> 3.8.0'

depends 'phpmyadmin', '~> 1.0.8'
