name             'dev-box'
maintainer       'Mykhailo Kokolius'
maintainer_email 'mickokolius@gmail.com'
license          'All rights reserved'
description      'dev box'
version          '0.0.2'

depends 'locale', '~> 1.1.0'
depends 'vim', '~> 2.0.2'
depends 'curl', '~> 2.0.3'

depends 'nginx', '~> 2.7.6'
depends 'mysql', '~> 8.0.2'
depends 'imagemagick', '~> 0.2.3'
depends 'java', '~> 1.42.0'
depends 'elasticsearch', '~> 2.3.2'
depends 'logstash', '~> 0.12.0'
depends 'postfix', '~> 3.8.0'

depends 'phpmyadmin', '~> 1.0.8'
