<?php echo $this->render('controls/header.phtml'); ?>

<div class="grid-container">
    <div class="grid-100 right bottom-10">
        <a class="mbox violet-btn" href="<?= $this->h()->url()->build('/admin/theme-edit-wnd'); ?>">
            <?php echo $this->t->_('add_new_theme'); ?>
        </a>
    </div>
    <div class="grid-100">
        <table id="themes-list" class="tablesorter" cellpadding="3" cellspacing="1">
            <thead>
                <tr>
                    <th class="{sorter: false}" width="40px"><?php echo $this->t->_('id'); ?></th>
                    <th><?php echo $this->t->_('status'); ?></th>
                    <th><?php echo $this->t->_('name'); ?></th>
                    <th><?php echo $this->t->_('ua'); ?></th>
                    <th><?php echo $this->t->_('ru'); ?></th>
                    <th class="{sorter: false}" width="36px"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->allThemes as $key => $value): ?>
                    <tr align="center" class="theme-<?php echo $value['id']; ?>">
                        <td><?php echo $value['id']; ?></td>
                        <td><?php echo $value['status']; ?></td>
                        <td><?php echo $value['name']; ?></td>
                        <td><?php echo $value['ua']; ?></td>
                        <td><?php echo $value['ru']; ?></td>
                        <td>
                            <a class="mbox" href="<?= $this->h()->url()->build('/admin/theme-edit-wnd', array('id' => $value['id'])); ?>">
                                <img style="cursor:pointer;" src="<?php echo $this->baseUrl ?>/public/theme/user/table/edit.png" />
                            </a>
                            <a class="mbox" href="<?= $this->h()->url()->build('/admin/theme-delete-wnd', array('id' => $value['id'])); ?>">
                                <img style="cursor:pointer;" src="<?php echo $this->baseUrl ?>/public/theme/user/table/remove.png" />
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
</div>
</div>

<?php echo $this->render('controls/footer.phtml'); ?>
