<?php echo $this->render('controls/header.phtml'); ?>
<div class="grid-container">
    <div class="breadcrumbs grid-100" itemprop="breadcrumb">
        <a href="<?= $this->h()->url()->build('/'); ?>"><?php echo $this->t->_('main_page_link'); ?></a> &raquo;
        <?php echo $this->t->_('resend_password'); ?>
        <div class="underline"></div>
    </div>

    <div class="grid-100 form-center-allign">
        <?php echo $this->resendPasswordForm; ?>
    </div>
</div>
<?php  echo $this->render('controls/footer.phtml'); ?>
