<div id="popup-wnd-data-content" class="popup-wnd-user-upload-avatar-size">
    <?php echo $this->render('controls/emptyheader.phtml'); ?>
    <script>
        var img, ias, ias2;
        var uploadBtnTitle = '<?php echo $this->t->_('load_image_btn'); ?>';
        $(document).ready(function(){
            $("#edit-avatar").click(function(){
                $('#thumbnail').imgAreaSelect({
                    disable: true,
                    hide: true
                });
                $('#mtest').imgAreaSelect({
                    disable: true,
                    hide: true
                });
                $("#start-upload-content").show();
                $("#upload-proces-content").hide();
                $("#upload-resize-content").hide();
                $("#avataredit").show();
            });
            var uploader = new qq.FileUploader({
                element: document.getElementById("file-uploader"),
                action: baseUrl + "/user/uploadphoto",
                debug: false,
                onSubmit: function(id, fileName){
                    startUploadImages(id, fileName);
                },
                onComplete: function(id, fileName, responseJSON){
                    endUploadImages(id, fileName, responseJSON);
                }
            });
            var uploader = new qq.FileUploader({
                element: document.getElementById("upload-other-img"),
                action: baseUrl + "/user/uploadphoto",
                debug: false,
                onSubmit: function(id, fileName){
                    startUploadImages(id, fileName);
                },
                onComplete: function(id, fileName, responseJSON){
                    endUploadImages(id, fileName, responseJSON);
                }
            });
            $('.close-popup-wnd').click(function() {
                $('#thumbnail').imgAreaSelect({
                    disable: true,
                    hide: true
                });
                $('#mtest').imgAreaSelect({
                    disable: true,
                    hide: true
                });
            });
            $('#edit-save-button').click(function() {
                $('#thumbnail').imgAreaSelect({
                    disable: true,
                    hide: true
                });
                $('#mtest').imgAreaSelect({
                    disable: true,
                    hide: true
                });
                $("#upload-proces-content").show();
                $("#upload-resize-content").hide();
                $("#start-upload-content").hide();
                $("#avatarDetails").ajaxForm({
                    dataType: "json",
                    complete: function(response) {
                        var data = eval ("("+response.responseText+")");
                        $("#avatar-img").attr("src", data.imgSrc);
                        $('#thumbnail').imgAreaSelect({
                            disable: true,
                            hide: true
                        });
                        $('#mtest').imgAreaSelect({
                            disable: true,
                            hide: true
                        });
                        $("#avataredit").hide();
                        mboxRemove();
                    }
                });
                $("#avatarDetails").submit();
                return false;
            });
            $("body #mbox-overlay, #mbox-wnd-close, .close-popup-wnd").click(function(){
                $('#thumbnail').imgAreaSelect({
                    disable: true,
                    hide: true
                });
                $('#mtest').imgAreaSelect({
                    disable: true,
                    hide: true
                });
            });
        });
        function startUploadImages(id, fileName){
            $('#thumbnail').imgAreaSelect({
                disable: true,
                hide: true
            });
            $('#mtest').imgAreaSelect({
                disable: true,
                hide: true
            });
            $("#start-upload-content").hide();
            $("#upload-proces-content").show();
            $("#upload-resize-content").hide();
        }
        function endUploadImages(id, fileName, responseJSON){
            img = new Image();
            img.src = responseJSON.imgPath;
            $("#imgName").val(responseJSON.imgName);
            $("#folder").val(responseJSON.folder);
            setTimeout(function(){
                chakLoading();
            }, 300);
        }
        function chakLoading(carrent_el){
            if (img.complete == true){
                showResizeBox();
            }else{
                setTimeout(function(){
                    chakLoading( );
                }, 100);
            }
        }
        function showResizeBox() {
            $("#thumbnail").attr("src",  img.src);
            $("#thumbnail_avatar").attr("src",  img.src);
            $("#thumbnail_avatar_larg").attr("src",  img.src);
            $("#thumbnail_avatar_small").attr("src",  img.src);
            var MAX_WIDTH = 400;
            var MAX_HEIGHT = 260;
            var width = img.width;
            var height = img.height;
            var delta = ((width / MAX_WIDTH) > (height / MAX_HEIGHT)) ? width / MAX_WIDTH : height / MAX_HEIGHT;
            $("#thumbnail").width(Math.round(width / delta));
            $("#thumbnail").height(Math.round(height / delta));
            $("#start-upload-content").hide();
            $("#upload-proces-content").hide();
            $("#upload-resize-content").show();
            $('.popup-wnd-functional .select-photo').hide();
            $('.popup-wnd-functional .upload-photo').show();
            $('#thumbnail').imgAreaSelect({
                disable: false
            });
            $('#mtest').imgAreaSelect({
                disable: false
            });
            ias =  $('#thumbnail').imgAreaSelect({
                handles: true,
                instance: true,
                aspectRatio: '1:1.38',
                onSelectChange: previewLarge
            });
            ias2 =  $('#mtest').imgAreaSelect({
                handles: true,
                instance: true,
                aspectRatio: '1:1',
                onSelectChange: previewSmall
            });
            iasInit();
            ias2Init();
        }
        function iasInit(){
            if($('#thumbnail').width() > ($('#thumbnail').height() / 1.38)) {
                var height = Math.round($('#thumbnail').height() * 0.9);
                var y1 = Math.round( ($('#thumbnail').height() - height) / 2);
                var y2 = y1 + height;
                var width = Math.round(height / 1.38);
                var x1 = Math.round( ($('#thumbnail').width() - width) / 2);
                var x2 = x1 + width;
            } else {
                var width = Math.round($('#thumbnail').width() * 0.9);
                var x1 = Math.round( ($('#thumbnail').width() - width) / 2);
                var x2 = x1 + width;
                var height = Math.round(width * 1.38);
                var y1 = Math.round( ($('#thumbnail').height() - height) / 2);
                var y2 = y1 + height;
            }
            ias.setSelection(x1, y1, x2, y2, true);
            ias.setOptions({
                show: true
            });
            ias.update();
            previewLarge($('#thumbnail'), ias.getSelection());
        }
        function ias2Init(){
            var y1 = 30;
            var y2 = 189;
            var x1 = 0;
            var x2 = 159;
            ias2.setSelection(x1, y1, x2, y2, true);
            ias2.setOptions({
                show: true
            });
            ias2.update();
            previewSmall($('#thumbnail_avatar'), ias2.getSelection());
        }
        function previewLarge(img, selection) {
            if (!selection.width || !selection.height)
                return;
            var scaleAvatarX = 159 / selection.width;
            var scaleAvatarY = 219 / selection.height;
            $('#thumbnail_avatar').css({
                width: Math.round(scaleAvatarX * $("#thumbnail").width()) + 'px',
                height: Math.round(scaleAvatarY * $("#thumbnail").height()) + 'px',
                marginLeft: '-' + Math.round(scaleAvatarX * selection.x1) + 'px',
                marginTop: '-' + Math.round(scaleAvatarY * selection.y1) + 'px'
            });
            $('#w').val(selection.width);
            $('#h').val(selection.height);
            $('#x1').val(selection.x1);
            $('#y1').val(selection.y1);
            $('#x2').val(selection.x2);
            $('#y2').val(selection.y2);
            previewSmall($('#thumbnail_avatar'), ias2.getSelection());
        }
        function previewSmall(img, selection) {
            if (!selection.width || !selection.height)
                return;
            var scaleAvatarXSmall = 50 / selection.width;
            var scaleAvatarYSmall = 50 / selection.height;
            var wkoef = $("#thumbnail").width() / $("#thumbnail_avatar").width();
            var hkoef = $("#thumbnail").height() / $("#thumbnail_avatar").height();
            var marginLeftSmall = scaleAvatarXSmall * (selection.x1 + $('#x1').val() / wkoef);
            var marginTopSmall = scaleAvatarYSmall * (selection.y1 + $('#y1').val() / hkoef);
            $('#thumbnail_avatar_small').css({
                width: Math.round(scaleAvatarXSmall * $("#thumbnail_avatar").width()) + 'px',
                height: Math.round(scaleAvatarYSmall * $("#thumbnail_avatar").height()) + 'px',
                marginLeft: '-' + Math.round(marginLeftSmall) + 'px',
                marginTop: '-' + Math.round(marginTopSmall) + 'px'
            });
            $('#s_w').val(selection.width);
            $('#s_h').val(selection.height);
            $('#s_x1').val(selection.x1);
            $('#s_y1').val(selection.y1);
            $('#s_x2').val(selection.x2);
            $('#s_y2').val(selection.y2);
        }
    </script>
    <div class="popup-wnd-header"><?php echo $this->t->_('uppload_avatar'); ?></div>
    <div class="popup-wnd-content" style="display: inline-block; height: 310px; width: 740px">
        <div id="start-upload-content" class="window_content">
            <div class="upload-info">
                <?php echo $this->t->_('select_photo_from_your_pc_msg'); ?>
            </div>
            <div class="upload-functional">
                <a id="file-uploader" style="cursor: pointer;"><?php echo $this->t->_('load_image_btn'); ?></a>
            </div>
        </div>

        <div id="upload-proces-content" class="window_content" style="display: none;">
            <div class="upload-info">
                <?php echo $this->t->_('supported_formats_msg'); ?>
            </div>
            <div class="upload-loading">
                <img src="<?php echo $this->baseUrl; ?>/public/theme/ajaxLoader.gif"/>
                <div style="padding-top: 30px;">
                    <?php echo $this->t->_('pleas_wait_loading_is_in_process_msg'); ?>
                </div>
            </div>
        </div>

        <div id="upload-resize-content" class="window_content" style="display: none; margin-left: 10px; position: relative; height: 300px;">
            <div class="finaledit_help">
                <?php echo $this->t->_('select_haw_your_avatar_will_look_like_msg'); ?>
            </div>
            <table width="99%">
                <tr>
                    <td valign="top" class="origwrap">
                        <div class="edit_orig"><img id="thumbnail" /></div>
                    </td>
                    <td></td>
                    <td>
                        <div class="edit_step2">
                            <div id="mtest" style="float:left; position:relative; margin-right: 10px; overflow:hidden; width:159px; height:219px;"><img id="thumbnail_avatar"/></div>
                            <div style="float:left; position:relative; overflow:hidden; width:50px; height:50px;"><img id="thumbnail_avatar_small"/></div>
                        </div>
                        <div class="clear"></div>
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <div class="popup-wnd-functional">
        <div class="select-photo">
            <input class="close-popup-wnd" type="button" value="<?php echo $this->t->_('cancel_btn'); ?>">
        </div>
        <div class="upload-photo" style="display: none;">
            <form id="avatarDetails" name="avatarDetails" action="<?= $this->h()->url()->build('/user/saveavatar'); ?>" method="post">
                <input type="hidden" id="imgName" name="imgName" value=""/>
                <input type="hidden" id="folder" name="folder" value=""/>
                <input type="hidden" name="x1" value="" id="x1" />
                <input type="hidden" name="y1" value="" id="y1" />
                <input type="hidden" name="x2" value="" id="x2" />
                <input type="hidden" name="y2" value="" id="y2" />
                <input type="hidden" name="w" value="" id="w" />
                <input type="hidden" name="h" value="" id="h" />
                <input type="hidden" name="s_x1" value="" id="s_x1" />
                <input type="hidden" name="s_y1" value="" id="s_y1" />
                <input type="hidden" name="s_x2" value="" id="s_x2" />
                <input type="hidden" name="s_y2" value="" id="s_y2" />
                <input type="hidden" name="s_w" value="" id="s_w" />
                <input type="hidden" name="s_h" value="" id="s_h" />
                <input type="submit" class="button" name="upload_thumbnail" value="save" style="display: none;"/>
            </form>
            <a id="upload-other-img" class="violet-btn"><?php echo $this->t->_('load_image_btn'); ?></a>
            <input id="edit-save-button" type="button" value="<?php echo $this->t->_('save_btn'); ?>">
            <input class="close-popup-wnd" type="button" value="<?php echo $this->t->_('cancel_btn'); ?>">
        </div>
    </div>

    <?php echo $this->render('controls/emptyfooter.phtml'); ?>
</div>