<?php if (!$this->item): ?>
    <?php $this->item = ($this->itemXml != '' && $this->itemXml->item != '') ? $this->itemXml->item : 'square'; ?>
<?php endif; ?>

<?php $borderClass = ($this->item == 'circle') ? 'circle' : 'square'; ?>
<?php $imgAlt = $this->t->_($this->item) . '. ' . $this->productName; ?>

<div class="mousepad">
    <div class="<?php echo $this->item ?>">
        <div class="content size ">
            <span class="border size"></span>
            <?php if($this->item == 'circle'): ?>
                <?php $this->h()->image()->getSmallInBoxImgPreview(2.76328, $this->itemXml, 'main', $imgAlt, 13, 0); ?>
            <?php else: ?>
                <?php $this->h()->image()->getSmallInBoxImgPreview(2.76328, $this->itemXml, 'main', $imgAlt, 0, 0); ?>
            <?php endif; ?>
        </div>
    </div>
</div>
