<div id="popup-wnd-data-content" class="popup-wnd-dialog-size">
    <?php echo $this->render('controls/emptyheader.phtml'); ?>

    <script>
        $(document).ready(function(){
            $('.delete-product-btn').click(function() {
                $.ajax({
                    type: "POST",
                    url: baseUrl + "/admin/delete-product",
                    data: {
                        id: '<?php echo $this->id; ?>'
                    },
                    success: function(data) {
                        reLoadProducts();
                        mboxRemove();
                    }
                });
            });
        });
    </script>

    <div id="popup-wnd-delete-theme">
        <div class="popup-wnd-header"><?php echo $this->t->_('delete_product_item'); ?></div>
        <div class="popup-wnd-warn-msg">
            <?php echo $this->t->_('do_you_realy_wont_to_delete_carrent_product_item')?>?
        </div>
        <div class="popup-wnd-functional">
            <input class="delete-product-btn" type="button" value="<?php echo $this->t->_('yes'); ?>">
            <input class="close-popup-wnd" type="button" value="<?php echo $this->t->_('no'); ?>">
        </div>
    </div>

    <?php echo $this->render('controls/emptyfooter.phtml'); ?>
</div>
