<?php if($this->tracking): ?>
    <?php if(isset($this->gaEvent['value'])): ?>
        <?php $this->gaEvent['value'] = (int) $this->gaEvent['value']; ?>
    <?php endif; ?>
    <script type="text/javascript">
        $(document).ready(function(){
            ga(
                'send',
                'event',
                <?php echo "'{$this->gaEvent['category']}'"; ?>
                <?php echo ", '{$this->gaEvent['action']}'"; ?>
                <?php echo (isset($this->gaEvent['label'])) ?  ", '{$this->gaEvent['label']}'" : ''; ?>
                <?php echo (isset($this->gaEvent['value'])) ?  ", '{$this->gaEvent['value']}'" : ''; ?>
            );
        });
    </script>
<?php endif; ?>
