<?php if(!$this->item):?>
    <?php $this->item = ($this->itemXml != '' && $this->itemXml->item != '') ? $this->itemXml->item : 'mantshirt'; ?>
<?php endif; ?>

<?php $imgAlt = $this->t->_($this->item) . '. ' . $this->productName; ?>

<div class="tshirt">
    <div class="<?php echo $this->item ?> ">
        <div class="content">
            <?php $this->h()->image()->getSmallInBoxImgPreview(2.13, $this->itemXml, 'front', $imgAlt, 0, 0); ?>
        </div>
    </div>
</div>

