<div class="cup">
<?php if ($this->itemXml->template == '4'): ?>
    <div class="long">
        <div class="cup-head"></div>
        <div class="content size">
            <span class="border size"></span>
            <?php $this->h()->image()->getInBoxImg($this->itemXml, 'main'); ?>
        </div>
    </div>
<?php endif; ?>
<?php if ($this->itemXml->template == '5'): ?>
    <script type="text/javascript">
        function showSide(side) {
            if(side == 'left') {
                $(".cup .left").show();
                $(".cup .right").hide();
            }
            if(side == 'right') {
                $(".cup .right").show();
                $(".cup .left").hide();
            }
        }
    </script>
    <div class="left show">
        <div class="position">
            <div class="content size">
                <?php $this->h()->image()->getInBoxImg($this->itemXml, 'left'); ?>
            </div>
        </div>
        <div class="functional">
            <?php echo $this->t->_('left') ?> |
            <a href="javascript:showSide('right');">
                <?php echo $this->t->_('right') ?>
            </a>
        </div>
    </div>
    <div class="right">
        <div class="position">
            <div class="content size">
                <?php $this->h()->image()->getInBoxImg($this->itemXml, 'right'); ?>
            </div>
        </div>
        <div class="functional">
            <a href="javascript:showSide('left');">
                <?php echo $this->t->_('left') ?>
            </a> |
            <?php echo $this->t->_('right') ?>
        </div>
    </div>
<?php endif; ?>
</div>
