<?php echo $this->render('controls/emptyheader.phtml'); ?>


<script>
initRTE('<i>This is some <b>preloaded</b> content</i>', '../public/stylesheets/texteditor.css');
</script>

<!--
<script language="javascript" type="text/javascript">
	var	button_name = "Зберегти";
	var	text_in_time = "document"; //.getElementById("div_and_text").innerHTML;
</script>

<div id="mess" name="mess" style="color:#000000; width:400px; height:572px; vertical-align:middle; text-align:center; background-color:#FFFF00; z-index:1005;">
	<script>
		initRTE(text_in_time, '../public/stylesheets/texteditor.css');
	</script>
</div>

<script language="javascript" type="text/javascript">
	document.getElementById("mess").style.left = "100px";
	document.getElementById("mess").style.top = "100px";
	document.getElementById("mess").style.visibility = "visible";
</script>
-->

<?php echo $this->render('controls/emptyfooter.phtml'); ?>