<?php if(!$this->item): ?>
    <?php $this->item = ($this->itemXml != '' && $this->itemXml->item != '') ? $this->itemXml->item : 'cork'; ?>
<?php endif; ?>

<?php $borderImg = (in_array($this->item, array('cork', 'square', 'rubber'))) ? 'border' : 'borderCircle'; ?>

<div class="trivet">
    <div class="content size">
        <?php $this->h()->image()->buildImgHolder('main', 1, $this->itemXml, 'size-origin-trivet', "trivet/{$borderImg}.png") ?>
    </div>
    <div class="functional-btn" id="btn_1">
        <?php echo $this->render('produces/controls/button.phtml') ?>
    </div>
</div>
