<?php $templateId = ($this->itemXml && $this->itemXml->template) ? $this->itemXml->template : '4'; ?>

<div class="cup">
    <div class="constructor template-<?php echo $templateId; ?>">
        <div class="template" data-template-id="template-<?php echo $templateId; ?>">
            <?php foreach ($this->productsTemplatesList as $template): ?>
                <div id="cup-templates-selector">
                    <img id="cup-<?php echo $template['name']?>" data-template-id="<?php echo $template['id']?>" class="<?php echo $template['name']; ?>"  src="<?php $this->h()->static()->path('produces/cup/'.$template['name'].'.png'); ?>" />
                </div>
            <?php endforeach; ?>
        </div>
        <div class="long">
            <div class="markup-img"></div>
            <div class="content">
                <?php $this->h()->image()->buildImgHolder('main', 1, $this->itemXml, 'size-origin-cup-long', 'cup/borderLarge.png') ?>
            </div>
            <div class="functional-btn" id="btn_1"><?php echo $this->render('produces/controls/button.phtml'); ?></div>
        </div>

        <div class="double">
            <div class="left">
                <div class="functional-btn" id="btn_2"><?php echo $this->render('produces/controls/button.phtml'); ?></div>
                <div class="image-box">
                    <?php $this->h()->image()->buildImgHolder('left', 2, $this->itemXml, 'size-origin-cup-double', 'cup/borderDouble.png') ?>
                </div>
                <div class="functional">
                    <?php echo $this->t->_('left') ?> | <a href="javascript:showSide('right');"><?php echo $this->t->_('right') ?></a>
                </div>
            </div>
            <div class="right">
                <div class="functional-btn" id="btn_3"><?php echo $this->render('produces/controls/button.phtml'); ?></div>
                <div class="image-box">
                    <?php $this->h()->image()->buildImgHolder('right', 3, $this->itemXml, 'size-origin-cup-double', 'cup/borderDouble.png') ?>
                </div>
                <div class="functional">
                    <a href="javascript:showSide('left');"><?php echo $this->t->_('left') ?></a> | <?php echo $this->t->_('right') ?>
                </div>
            </div>
        </div>
    </div>
</div>
