<?php if($this->img_count > 1): ?>

	<?php if($this->current_page > 1): ?>
		<a href="javascript:showImageOnPage('1')"><?php echo $this->t->_('first'); ?></a>
		&nbsp;&nbsp;
		<a href="javascript:showImageOnPage('<?php echo $this->current_page - 1; ?>')"><?php echo $this->t->_('previos'); ?></a>
	<?php endif; ?>

	<?php if($this->current_page - 3 > 1): ?> ... <?php else: ?> &nbsp;&nbsp;&nbsp; <?php endif; ?>

	<?php for($i = $this->current_page - 3; $i < $this->current_page + 4; $i++): ?>
		<?php if(($i > 0) && ($i < ($this->img_count + 1))) :?>
			<?php if($i != $this->current_page): ?>
				<a href="javascript:showImageOnPage('<?php echo $i; ?>')"><?php echo $i; ?></a>
			<?php else: ?>
				<?php echo $i; ?>
			<?php endif; ?>
		<?php endif; ?>
	<?php endfor; ?>

	<?php if(($this->current_page + 4) < ($this->img_count + 1)): ?> ... <?php else: ?> &nbsp;&nbsp;&nbsp; <?php endif; ?>

	<?php if($this->current_page < $this->img_count): ?>
		<a href="javascript:showImageOnPage('<?php echo $this->current_page + 1; ?>')"><?php echo $this->t->_('next'); ?></a>
		&nbsp;&nbsp;
		<a href="javascript:showImageOnPage('<?php echo $this->img_count; ?>')"><?php echo $this->t->_('last'); ?></a>
	<?php endif; ?>

<?php endif; ?>

