<div class="postcard">
    <div class="tabs postcard-tab-front">
        <?php if($this->showFullInfo): ?><div onclick="mark(2);" class="tab left-tab"><?php echo $this->t->_('inner_page') ?></div><?php endif; ?>
        <div class="content content-img-left">
            <?php $this->h()->image()->buildImgHolder('main', 1, $this->itemXml, 'size-origin-postcard', 'postcard/border.png') ?>
        </div>
        <div class="studio-funcional-btn right-functional-btn"><?php echo $this->render('produces/controls/button.phtml') ?></div>
        <?php if($this->showFullInfo): ?>
            <div class="side-links">
                <?php echo $this->t->_('main_page') ?> | <a href="javascript:mark(2);"><?php echo $this->t->_('inner_page') ?></a> | <a href="javascript:mark(3);"><?php echo $this->t->_('last_page') ?></a>
            </div>
        <?php endif; ?>
    </div>
    <?php if($this->showFullInfo): ?>
        <div class="tabs hidden postcard-tab-middle">
            <div onclick="mark(1);" class="tab left-tab"><?php echo $this->t->_('main_page') ?></div>
            <div onclick="mark(3);" class="tab right-tab"><?php echo $this->t->_('last_page') ?></div>
            <div class="studio-funcional-btn left-functional-btn"><?php echo $this->render('produces/controls/button.phtml') ?></div>
            <div class="content content-img-left">
                <?php $this->h()->image()->buildImgHolder('inner', 2, $this->itemXml, 'size-origin-postcard', 'postcard/border.png') ?>
            </div>
            <div class="content-img-right">
                <div class="size-origin-postcard text-box">
                    <img id="postcardTextBox" class="content-image-border size-origin-postcard no-border" src="<?php $this->h()->static()->path('produces/postcard/border.png') ?>">
                    <div class="text-box-zoomed postcard-content-zoom"><div id="postcardText"><?php if($this->itemXml): echo $this->itemXml->content->text; else: ?><?php echo $this->t->_('click_for_text') ?><?php endif ?></div></div>
                </div>
            </div>
            <div class="studio-funcional-btn right-functional-btn">
                <?php if(!$this->itemId): ?>
                    <img class="basketbtn" src="<?php $this->h()->static()->path('produces/basketbtn.png') ?>">
                <?php else: ?>
                    <img class="basketbtn" src="<?php $this->h()->static()->path('produces/savebasketbtn.png') ?>">
                <?php endif ?>
                <img class="editbtn" src="<?php $this->h()->static()->path('produces/editbtn.png') ?>">
            </div>
            <div class="side-links">
                <a href="javascript:mark(1);"><?php echo $this->t->_('main_page') ?></a> | <?php echo $this->t->_('inner_page') ?> | <a href="javascript:mark(3);"><?php echo $this->t->_('last_page') ?></a>
            </div>
        </div>
        <div class="tabs hidden postcard-tab-back">
            <div onclick="mark(2);" class="tab left-tab"><?php echo $this->t->_('inner_page') ?></div>
            <div class="content-img-left">
                <div class="size-origin-postcard">
                    <img class="content-image-border size-origin-postcard" src="<?php $this->h()->static()->path('produces/postcard/postcardBack.png') ?>">
                </div>
            </div>
            <div class="studio-funcional-btn right-functional-btn">
                <?php if(!$this->itemId): ?>
                    <img class="basketbtn" src="<?php $this->h()->static()->path('produces/basketbtn.png') ?>">
                <?php else: ?>
                    <img class="basketbtn" src="<?php $this->h()->static()->path('produces/savebasketbtn.png') ?>">
                <?php endif ?>
            </div>
            <div class="side-links">
                <a href="javascript:mark(1);"><?php echo $this->t->_('main_page') ?></a> | <a href="javascript:mark(2);"><?php echo $this->t->_('inner_page') ?></a> | <?php echo $this->t->_('last_page') ?>
            </div>
        </div>
    <?php endif; ?>
</div>
