<div id="popup-wnd-data-content" class="popup-wnd-produces-productpreview-size">
    <style type="text/css">
        .previewImg {
            padding: 1px;
            border: 1px solid #ffffff;
            width: 100px;
            height: 75px;
        }
    </style>
    <script type="text/javascript">
        $(".previewImg").click(function(){
            $("#viewImg").attr("src", $(this).attr("src"));
            $(".previewImg").css({"border": "1px solid #ffffff"});
            $(this).css({"border": "1px solid #744B54"});
        });
    </script>

    <div class="popup-wnd-header">
        <?php echo $this->t->_($this->item); ?>
    </div>

    <div style="padding: 20px 20px 10px 20px;">
        <img id="viewImg" alt="" src="<?php echo $this->baseUrl; ?>/public/theme/produces/tovlist/<?php echo $this->group ?>/<?php echo $this->item ?>/1.jpg" width="480" height="360">
    </div>
    <div style="text-align: center;">
        <img class="previewImg" style="border: 1px solid #744B54; cursor: pointer;" src="<?php echo $this->baseUrl; ?>/public/theme/produces/tovlist/<?php echo $this->group ?>/<?php echo $this->item ?>/1.jpg">
        <?php for($i = 2; $i <= 4; $i++): ?>
            <?php if(file_exists('./public/theme/produces/tovlist/'.$this->group.'/'.$this->item."/$i.jpg")): ?>
                <img class="previewImg" style="cursor: pointer;" src="<?php echo $this->baseUrl; ?>/public/theme/produces/tovlist/<?php echo "$this->group/$this->item/$i" ?>.jpg"/>
            <?php endif; ?>
        <?php endfor; ?>
    </div>
</div>