<script language="javascript" type="text/javascript">
    <?php if(!count($this->allAlbums)): ?>
        $("#deleteAlbumForm").hide();
    <?php else: ?>
        $("#deleteAlbumForm").show();
    <?php endif; ?>
        var album_dialog = "<?php echo $this->t->_('album_dialog'); ?>";
        var album_name  = "<?php echo $this->t->_('album_name'); ?>";
        var create_album_btn = "<?php echo $this->t->_('create_album_btn'); ?>";
        var cancel_album_btn = "<?php echo $this->t->_('cancel_album_btn'); ?>";
</script>
<div class="breadcrumbs" itemprop="breadcrumb">
    <?php echo $this->t->_('albums'); ?>
    <div class="underline"></div>
</div>

<div style="padding-top: 10px;">
    <?php if($this->hasNotSortedImages): ?>
        <div style="float: left; width: 184px; height: 140px; text-align: center;">
            <div style="height:120px">
                <a href="javascript:loadAlbum('0');">
                    <img src="<?php echo $this->baseUrl; ?>/public/theme/user/photoAlbum.png" class="no-border"/>
                </a>
            </div>
            <div>
                <input type="checkbox" id="chImgName_0" class="chImgName" />&nbsp;
                <font style="font-size:16px"><?php echo $this->t->_('not_selected'); ?></font>
            </div>
        </div>
    <?php endif; ?>
    <?php foreach ($this->allAlbums as $key => $value): ?>
    <div style="float: left; width: 184px; height: 140px; text-align: center;">
        <div style="height:120px">
            <a href="javascript:loadAlbum('<?php echo $value["id"]; ?>');">
                <img src="<?php echo $this->baseUrl; ?>/public/theme/user/photoAlbum.png" class="no-border"/>
            </a>
        </div>
        <div>
            <input type="checkbox" id="chImgName_<?php echo $value['id']; ?>" class="chImgName" />&nbsp;
            <font style="font-size:16px"><?php echo $value['title']; ?></font>
        </div>
    </div>
    <?php endforeach; ?>
    <div class="clear"></div>
</div>
<div style="padding-top: 10px; text-align: right;">
    <a id="addAlbumForm" class="mbox violet-btn" href="<?= $this->h()->url()->build('/user/createalbumwnd'); ?>">
        <?php echo $this->t->_('add_album'); ?>
    </a>
    <a id="deleteAlbumForm" class="mbox violet-btn" href="<?= $this->h()->url()->build('/user/deletealbumswnd'); ?>">
        <?php echo $this->t->_('delete_album'); ?>
    </a>
</div>
