<div id="popup-wnd-data-content" class="popup-wnd-change-pass-size">
    <?php echo $this->render('controls/emptyheader.phtml'); ?>

    <script>
        $(document).ready(function(){
            $('.change-password-btn').click(function(){
                var form = $('#change-password-form');
                form.find('.errors').remove();
                $.ajax({
                    url: form.attr('action'),
                    type: form.attr('method'),
                    dataType: "json",
                    data: form.serialize(),
                    success: function (data) {
                        if (data.status == 'error'){
                            for(key in data.errors){
                                $('input[name=' + key + ']').after('<span class="errors">' + data.errors[key] + '</span>');
                            }
                        } else {
                            mboxRemove();
                        }
                    }
                });
            });
        });
    </script>

    <div>
        <div class="popup-wnd-header"><?php echo $this->t->_('change_password'); ?></div>
        <div>
            <?php echo $this->resetPassForm; ?>
        </div>
        <div class="popup-wnd-functional">
            <input class="change-password-btn" type="button" value="<?php echo $this->t->_('save'); ?>">
            <input class="close-popup-wnd" type="button" value="<?php echo $this->t->_('cancel'); ?>">
        </div>
    </div>

    <?php echo $this->render('controls/emptyfooter.phtml'); ?>
</div>