<?php echo $this->render('controls/header.phtml'); ?>

<script>
    $(document).ready(function(){
        $("#login-for-order").click(function() {
            var loginEmail = $("#order-user-email").val();
            var loginPassword = $("#order-user-password").val();

            $('.login-error-msg').hide();

            if((loginEmail != '') && (loginPassword != '')){
                $('.popup-wnd-content').removeClass('popup-wnd-content-errors');
                $('.popup-wnd-errors').html('');

                $.ajax({
                    type: "POST",
                    url: baseUrl + "/user/login-on-create-order",
                    data: {
                        email: loginEmail,
                        password: loginPassword
                    },
                    success: function(data) {
                        if (data.status == 'success') {
                            location.reload();
                        } else {
                            $('.login-empty').hide();
                            $('.login-error-msg').show();
                            $('.login-error').show();
                        }
                    }
                });
            }else{
                $('.login-error').hide();
                $('.login-error-msg').show();
                $('.login-empty').show();
            }
        });
    });
</script>

<div class="grid-container">
    <div id="make-order" class="confirm-order">
        <?php if(!$this->islogin): ?>
            <div class="grid-50 mobile-grid-100">
                <ul>
                    <li class="title">
                        <span class="icon returned-customer"></span>
                        <?php echo $this->t->_('has_account') ?>
                    </li>
                    <li class="login-error-msg center hide">
                        <span class="login-error errors"><?php echo $this->t->_('error_message_incorrect') ?></span>
                        <span class="login-empty errors"><?php echo $this->t->_('error_message_missed') ?></span>
                    </li>
                    <li>
                        <label>
                            <?php echo $this->t->_('email') ?>
                        </label>
                        <input type="text" value="" id="order-user-email">
                    </li>
                    <li>
                        <label>
                            <?php echo $this->t->_('password') ?>
                        </label>
                        <input type="password" value="" id="order-user-password">
                    </li>
                    <li>
                        <button id="login-for-order" class="green-btn" type="button">
                            <?php echo $this->t->_('login') ?>
                        </button>
                    </li>
                </ul>
            </div>
            <?php $userInfoCss = 'grid-50'; ?>
        <?php else: ?>
            <?php $userInfoCss = 'grid-100'; ?>
        <?php endif; ?>

        <form name="<?php echo $this->orderForm->getName(); ?>" id="create-order-form"
              method="<?php echo $this->orderForm->getMethod(); ?>">

            <div class="<?php echo $userInfoCss; ?>">
                <ul>
                    <li class="title">
                        <span class="icon new-user"></span>
                        <?php if(!$this->islogin): ?>
                            <?php echo $this->t->_('first_time') ?>
                        <?php else: ?>
                            <?php echo $this->t->_('thank_you_for_trust') ?>
                        <?php endif; ?>
                    </li>
                    <li>
                        <?php echo $this->orderForm->getElement('user_name')->render() ?>
                    </li>
                    <li>
                        <?php echo $this->orderForm->getElement('phone')->render() ?>
                    </li>
                    <li>
                        <?php echo $this->orderForm->getElement('email')->render() ?>
                    </li>
                    <?php if(!$this->islogin): ?>
                        <li>
                            <?php echo $this->orderForm->getElement('password')->render() ?>
                        </li>
                        <li>
                            <?php echo $this->orderForm->getElement('confirm_password')->render() ?>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
            <div class="clear"></div>

            <div class="grid-50">
                <ul>
                    <li class="title">
                        <span class="icon delivery"></span>
                        <?php echo $this->t->_('delivery_method') ?>
                    </li>
                    <li>
                        <?php echo $this->orderForm->getElement('delivery')->render() ?>
                    </li>
                    <li>
                        <?php echo $this->orderForm->getElement('address')->render() ?>
                    </li>
                </ul>
            </div>

            <div class="grid-50">
                <ul>
                    <li class="title">
                        <span class="icon payment"></span>
                        <?php echo $this->t->_('payment_method') ?>
                    </li>
                    <li>
                        <?php echo $this->orderForm->getElement('payment')->render() ?>
                    </li>
                </ul>
            </div>

            <div class="clear"></div>
            <div class="grid-100" style="text-align: right; padding-bottom: 20px;">
                <button class="green-btn" type="submit">
                    <?php echo $this->t->_('confirm_order') ?>
                </button>
            </div>
        </form>

    </div>
</div>

<?php echo $this->render('controls/footer.phtml'); ?>
