<div id="popup-wnd-data-content" class="popup-wnd-dialog-size">
    <?php echo $this->render('controls/emptyheader.phtml'); ?>

    <script>
        $(document).ready(function(){
            var idListForDelete = "";
            var chImgName = $("#userImages").find(".chImgName:checked").each(function(){
                var elId = ($(this).attr("id").split("_"))[1];
                idListForDelete += (idListForDelete != "") ? ";"+elId : elId;
            });
            if(idListForDelete != "") {
                $('.popup-wnd-warn-msg').html('<?php echo $this->t->_('do_you_realy_wont_to_delete_selected_images')?>?');
                $('#delete-image-btn').css({'visibility': 'visible'});
                $('.remove-images-btn').click(function(){
                    $.ajax({
                        type: "POST",
                        url: baseUrl + "/user/deleteimages?v=" + baseVersion,
                        data: {
                            listId: idListForDelete
                        },
                        success: function(data) {
                            mboxRemove();
                            var albumId = ($("#currentAlbumId").length > 0) ? $("#currentAlbumId").val() : 0;
                            $("#userImages").load(
                                baseUrl + "/user/images?albumId=" + albumId + "&v=" + baseVersion,
                                function(){ reloadBox(); }
                            );
                        }
                    });

                    return false;
                });
            } else {
                $('.popup-wnd-warn-msg').html('<?php echo $this->t->_('you_didnt_select_image_for_delete')?>.');
                $('#delete-image-btn').hide();
                $('#delete-image-close-btn').show();
            }
        });
    </script>

    <div id="popup-wnd-delete-theme">
        <div class="popup-wnd-header"><?php echo $this->t->_('delete_images'); ?></div>
        <div class="popup-wnd-warn-msg"></div>
        <div class="popup-wnd-functional">
            <div id="delete-image-btn" style="visibility: hidden;">
                <input class="remove-images-btn" type="button" value="<?php echo $this->t->_('yes'); ?>">
                <input class="close-popup-wnd" type="button" value="<?php echo $this->t->_('no'); ?>">
            </div>
            <div id="delete-image-close-btn" class="hidden">
                <input class="close-popup-wnd" type="button" value="<?php echo $this->t->_('close'); ?>">
            </div>
        </div>
    </div>

    <?php echo $this->render('controls/emptyfooter.phtml'); ?>
</div>