<?php echo $this->render('controls/header.phtml'); ?>

<div class="grid-container">
    <div class="grid-55 mobile-grid-100">
        <div id="slider">
            <div id="feature-list-<?php echo count($this->publicProductsGroup) ?>">
                <ul id="tabs">
                    <?php foreach ($this->publicProductsGroup as $key => $value): ?>
                        <li class="<?php echo $value['name']; ?>">
                            <span class="rectangle <?php echo $value['name']; ?>R"></span>
                            <a href="javascript:;">
                                <span class="triangle <?php echo $value['name']; ?>T"></span>
                                <span class="title"><?php echo $this->t->_($value['name'], $this->supportLanguage); ?></span>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <ul id="output">
                    <?php foreach ($this->publicProductsGroup as $key => $value): ?>
                        <li>
                            <img src="<?php $this->h()->static()->path('home/slider-' . $value['name'] . '.jpg') ?>" alt="<?php echo $this->t->_($value['name']); ?>">
                            <a class="violet-btn t-slider-products-<?php echo $value['name']; ?>" href="<?= $this->h()->url()->build("/produces/products/group/{$value['name']}"); ?>"><?php echo $this->t->_('more_deteils') ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
    <div class="grid-45 mobile-grid-100">
        <div id="promo-info"><h1><?php echo $this->t->_('main_header'); ?></h1><div><?php echo $this->t->_('main_info'); ?></div></div>
        <div id="social-share-btn" class="home-page">
            <div class="vk"><div id="vk_like"></div><script type="text/javascript" src="//vk.com/js/api/openapi.js?105"></script><script type="text/javascript">VK.init({apiId: 2228139, onlyWidgets: true}); VK.Widgets.Like("vk_like", {type: "mini", height: 20});</script></div>
            <div class="fb"><div id="fb-root"></div><script>(function(d, s, id) {var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) return; js = d.createElement(s); js.id = id; js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=521117277930288"; fjs.parentNode.insertBefore(js, fjs);}(document, 'script', 'facebook-jssdk'));</script><div class="fb-like" data-href="<?php echo $this->requestFullUri ?>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div></div>
            <div class="google-plus"><div class="g-plusone" data-size="medium" data-href="<?php echo $this->requestFullUri ?>"></div><script type="text/javascript">window.___gcfg = {lang: 'en'};(function() {var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true; po.src = 'https://apis.google.com/js/platform.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);})();</script></div>
            <div class="tweeter"><a href="https://twitter.com/share" class="twitter-share-button" data-lang="en">Tweet</a><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s); js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></div>
        </div>
    </div>
</div><div class="clear"></div>

<div id="promo-partner-info">
    <div class="grid-container">
        <div class="grid-33">
            <div class="info">
                <div class="icon registration-icon"><?php echo $this->t->_('registration_icon') ?></div>
                <div class="text"><?php echo $this->t->_('registration_slogan') ?></div>
            </div>
        </div>
        <div class="grid-33">
            <div class="info">
                <div class="icon share-link-icon"><?php echo $this->t->_('share_link_icon') ?></div>
                <div class="text"><?php echo $this->t->_('share_link_slogan') ?></div>
            </div>
        </div>
        <div class="grid-33">
            <div class="info">
                <div class="icon earn-money-icon"><?php echo $this->t->_('earn_money_icon') ?></div>
                <div class="text"><?php echo $this->t->_('earn_money_slogan') ?></div>
            </div>
        </div><div class="clear"></div>
    </div><div class="clear"></div>
</div>

<div class="grid-container">
    <?php foreach ($this->publicProductsGroup as $key => $value): ?>
        <div class="grid-50 product-promo">
            <h2><?php echo $this->t->_($value['name'], $this->supportLanguage); ?></h2>
            <div>
                <div class="text">
                    <img class="img-products-promo" src="<?php $this->h()->static()->path('produces/index/' . $value['name'] . 'Small.jpg') ?>"
                         alt="<?php echo $this->t->_($value['name']); ?>" width="110" height="80" data-link-class="link-products-<?php echo $value['name']; ?>">
                    <?php echo $this->t->_($value['name'] . '_text'); ?>
                </div>
                <div class="link">
                    <a class="t-link-products-<?php echo $value['name']; ?> link-products-<?php echo $value['name']; ?>" href="<?= $this->h()->url()->build("/produces/products/group/{$value['name']}"); ?>">
                        <?php echo $this->t->_('more_deteils', $this->supportLanguage); ?>
                    </a>
                </div>
            </div>
        </div><?php if ((($key + 1) % 2) == 0): ?><div class="clear"></div><?php endif; ?>
    <?php endforeach; ?>
</div>

<?php echo $this->render('controls/footer.phtml'); ?>
