<form id="createOrderForm" name="<?php echo $this->userDataForm->getName(); ?>" method="<?php echo $this->userDataForm->getMethod(); ?>" action="<?php echo $this->userDataForm->getAction(); ?>">
    <dl class="zend_form">
        <?php echo $this->userDataForm->getElement('user_name')->render(); ?>
        <?php echo $this->userDataForm->getElement('phone')->render(); ?>
        <?php echo $this->userDataForm->getElement('email')->render(); ?>
        <?php echo $this->userDataForm->getElement('address')->render(); ?>
        <dd><input id="submit" type="submit" value="<?php echo $this->t->_('next_btn') . ' &raquo;'; ?>"></dd>
    </dl>
</form>

<?php
$this->gaEvent = ['category' => 'Замовлення', 'action' => 'Оплата', 'label' => 'Крок-3'];
echo $this->render('controls/ga/event.phtml');
?>
