<div id="popup-wnd-data-content" class="popup-wnd-dialog-size">
    <?php echo $this->render('controls/emptyheader.phtml'); ?>

    <script>
        $(document).ready(function(){
            $('.remove-tag-btn').click(function() {
                $.ajax({
                    type: "POST",
                    url: baseUrl + "/admin/tag-delete",
                    data: {
                        id: '<?php echo $this->tag->id; ?>'
                    },
                    success: function(data) {
                        $('tr.tag-<?php echo $this->tag->id; ?>').remove();
                        mboxRemove();
                    }
                });
            });
        });
    </script>

    <div id="popup-wnd-delete-tag">
        <div class="popup-wnd-header"><?php echo $this->t->_('delete_tag'); ?></div>
        <div class="popup-wnd-warn-msg">
            <?php echo $this->t->_('do_you_really_want_to_delete_tag')?> "<?php echo $this->tag->{$this->language}; ?>"?
        </div>
        <div class="popup-wnd-functional">
            <input class="remove-tag-btn" type="button" value="<?php echo $this->t->_('yes'); ?>">
            <input class="close-popup-wnd" type="button" value="<?php echo $this->t->_('no'); ?>">
        </div>
    </div>

    <?php echo $this->render('controls/emptyfooter.phtml'); ?>
</div>
