<?php if(!$this->item): ?>
    <?php $this->item = ($this->itemXml != '' && $this->itemXml->item != '') ? $this->itemXml->item : 'square'; ?>
<?php endif; ?>

<?php $borderClass = ($this->item == 'circle') ? 'circle' : 'square'; ?>
<?php $imgAlt = $this->t->_($this->item) . '. ' . $this->productsItem[$this->language]; ?>

<div class="mousepad">
    <div class="<?php echo $borderClass; ?>">
        <span class="border size"></span>
        <?php if($this->item == 'circle'): ?>
            <?php $this->h()->image()->getSmallInBoxImgView(1.135, $this->itemXml, 'main', $imgAlt, 0, -33); ?>
        <?php else: ?>
            <?php $this->h()->image()->getSmallInBoxImgView(1.300, $this->itemXml, 'main', $imgAlt, 0, 0); ?>
        <?php endif; ?>
    </div>
</div>
