<div id="popup-wnd-data-content" class="popup-wnd-login-size">
    <?php echo $this->render('controls/emptyheader.phtml'); ?>
    <script language="javascript">
        var incorretInputData = '<?php echo $this->t->_('error_message_incorrect'); ?>';
        var incorretMissedData = '<?php echo $this->t->_('error_message_missed'); ?>';
    </script>

    <div id="popup-wnd-login">
        <div class="popup-wnd-header"><?php echo $this->t->_('login'); ?></div>
        <div class="popup-wnd-content">
            <div class="popup-wnd-errors"></div>
            <dl class="zend_form">
                <dt id="user_name-label">
                    <label class="required" for="login_email"><?php echo $this->t->_('login_email'); ?>:</label>
                </dt>
                <dd id="user_name-element">
                    <input type="text" value="" id="login_email" name="login_email">
                </dd>

                <dt id="user_name-label">
                    <label class="required" for="login_password"><?php echo $this->t->_('password'); ?>:</label>
                </dt>
                <dd id="user_name-element">
                    <input type="password" value="" id="login_password" name="login_password">
                </dd>
            </dl>
        </div>
        <div class="popup-wnd-functional">
            <div class="additional-info">
                <a href="<?= $this->h()->url()->build('/user/resend-password'); ?>">
                    <?php echo $this->t->_('forget_pass'); ?>
                </a>
            </div>
            <input id="login-btn" type="button" value="<?php echo $this->t->_('login_btn'); ?>" >
            <input class="close-popup-wnd" type="button" value="<?php echo $this->t->_('cancel_btn'); ?>">
        </div>
    </div>

    <?php echo $this->render('controls/emptyfooter.phtml'); ?>
</div>