<?php if(!$this->item): ?>
    <?php $this->item = ($this->itemXml != '' && $this->itemXml->item != '') ? $this->itemXml->item : 'cork'; ?>
<?php endif; ?>

<?php $borderClass = (in_array($this->item, array('cork', 'square', 'rubber'))) ? 'square' : 'circle'; ?>

<div class="trivet">
    <div class="content size">
        <span class="border size <?php echo $borderClass?>"></span>
        <?php $this->h()->image()->getInBoxImg($this->itemXml, 'main') ?>
    </div>
</div>
