<?php if($this->item == ''): ?>
    <?php $this->item = 'mantshirt'; ?>
<?php endif; ?>

<?php $viewSide = ($this->itemXml->template == 2) ? 'back' : 'front'; ?>
<?php $imgAlt = $this->t->_($this->item) . '. ' . $this->productsItem[$this->language]; ?>

<div class="tshirt">
    <div class="template-<?php echo $this->itemXml->template; ?>">
        <?php if(($this->itemXml->template == 1) || ($this->itemXml->template == 3)): ?>
            <div class="front">
                <div class="sides <?php echo $this->item; ?> <?php echo $this->color ?>">
                    <div id="insert-img1" class="content size">
                        <?php $this->h()->image()->getSmallInBoxImgView(1, $this->itemXml, 'front', $imgAlt, 0, 0); ?>
                    </div>
                </div>
                <div class="functional">
                    <?php echo $this->t->_('front'); ?> |
                    <a href="javascript:showSide('back');">
                        <?php echo $this->t->_('back') ?>
                    </a>
                </div>
            </div>
        <?php endif; ?>
        <?php if(($this->itemXml->template == 2) || ($this->itemXml->template == 3)): ?>
            <div class="back">
                <div class="sides <?php echo $this->item; ?> <?php echo $this->color ?>">
                    <div id="insert-img2" class="content size">
                        <?php $this->h()->image()->getSmallInBoxImgView(1, $this->itemXml, 'back', $imgAlt, 0, 0); ?>
                    </div>
                </div>
                <div class="functional">
                    <a href="javascript:showSide('front');">
                        <?php echo $this->t->_('front') ?>
                    </a> |
                    <?php echo $this->t->_('back') ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
