<script type="text/javascript"> var albumName = "<?php echo $this->t->_('some_time'); ?>"; </script>
<div id="draggable-img-list">
    <div class="holder">
        <div class="albums">
            <div class="selected"><?php echo $this->t->_('my_photo'); ?></div>
            <div>
                <label><?php echo $this->t->_('album'); ?>:</label>
                <?php if ($this->islogin): ?>
                    <?php if($this->albumId): ?>
                        <a href="<?= $this->h()->url()->build('/produces/useralbum', array('height' => 254, 'width' => 352)); ?>" class="mbox">
                            <span id="selectedCurrentAlbum"><?php echo $this->albumTitle; ?></span>
                        </a>
                    <?php else: ?>
                        <a href="<?= $this->h()->url()->build('/produces/useralbum', array('height' => 254, 'width' => 352)); ?>" class="mbox">
                            <span id="selectedCurrentAlbum"><?php echo $this->t->_('not_selected'); ?></span>
                        </a>
                    <?php endif; ?>
                <?php else: ?>
                    <?php echo $this->t->_('not_selected'); ?>
                <?php endif; ?>
            </div>
            <div class="functional">
                <input type="hidden" id="currentAlbumId" name="currentAlbumId" value="<?php echo $this->albumId; ?>"/>
                <a id="add-photo" class="violet-btn" href="<?= $this->h()->url()->build('/user/uploadimageswnd'); ?>"><?php echo $this->t->_('upload_photo'); ?></a>
            </div>
        </div>

        <div id="help-msg">
            <div class="msg"><?php echo $this->t->_('grag_photo_to_placeholder'); ?></div>
            <div class="arrow-img"></div>
        </div>

        <table cellpadding="0" cellspacing="0">
            <tr class="img">
                <?php foreach ($this->imagesList as $key => $value): ?>
                <td align="center">
                    <?php if ($value['id'] != null): ?>
                        <div id="<?php echo $key; ?>" class="img-holder" align="center"><img src="<?php echo $value['path']; ?>" style="background: url(../../../../public/theme/img-bg.png);" /></div>
                        <?php if ($key == 0): ?><img id="upload-helper" class="hidden" src="<?php echo $this->baseUrl; ?>/public/theme/produces/uploadImgHelper<?php echo $this->language; ?>.png"/><?php endif; ?>
                    <?php elseif ($value['id'] == null): ?>
                        <div id="<?php echo $key; ?>" class="img-holder" align="center"><img src="<?php echo $value['path']; ?>" class="hidden" style="background: url(../../../../public/theme/img-bg.png);" /></div>
                        <?php if ($key == 0): ?><img id="upload-helper" src="<?php echo $this->baseUrl; ?>/public/theme/produces/uploadImgHelper<?php echo $this->language; ?>.png"/><?php endif; ?>
                    <?php endif; ?>
                </td>
                <?php endforeach; ?>
            </tr>
            <tr>
                <td colspan="4">
                    <div id="pagination"><?php echo $this->render('controls/ajaxPaging.phtml'); ?></div>
                </td>
            </tr>
        </table>
    </div>
</div>
