<?php echo $this->render('controls/header.phtml'); ?>

<script type="text/javascript">
    var saveBtnText= '<?php echo $this->t->_('save_btn'); ?>';
    var cancelBtnText= '<?php echo $this->t->_('cancel_btn'); ?>';
</script>
<div class="grid-container">
    <div class="breadcrumbs grid-100" itemprop="breadcrumb">
        <a href="<?= $this->h()->url()->build('/'); ?>"><?php echo $this->t->_('main_page_link'); ?></a> &raquo;
        <a href="<?= $this->h()->url()->build("/produces/products/group/{$this->group}"); ?>"><?php echo $this->t->_($this->group); ?></a> &raquo;
        <?php echo $this->t->_($this->item); ?>
    </div>
    <div id="dragImagesStudia" class="grid-100">
        <input type="hidden" id="group" name="group" value="<?php echo $this->group; ?>" />
        <input type="hidden" id="item" name="item" value="<?php echo $this->item; ?>" />
        <input type="hidden" id="template" name="template" value="<?php echo $this->templateId; ?>" />
        <?php if($this->itemId): ?>
            <input type="hidden" id="itemId" name="itemId" value="<?php echo $this->itemId; ?>" />
        <?php endif; ?>

        <?php echo $this->render('produces/controls/dragubleimage.phtml'); ?>

        <div class="create">
            <?php echo $this->render("controls/products/create/$this->group.phtml"); ?>
        </div>
    </div>
</div>

<?php echo $this->render('controls/footer.phtml'); ?>
