<div id="warranty-product" class="grid-100 grid-parent">
    <div class="message grid-100 mobile-grid-100">
        <?php echo $this->t->_('warranty_promo_msg'); ?>
        <div class="underline-dot" ></div>
    </div>
    <div class="grid-33 quality">
        <img src="<?php $this->h()->static()->path('warranty/quality.svg'); ?>" width="50px">
        <div class="item-title"><?php echo $this->t->_('warranty_quality'); ?></div>
        <p><?php echo $this->t->_('warranty_quality_text'); ?></p>
    </div>
    <div class="grid-33 delivery">
        <img src="<?php $this->h()->static()->path('warranty/delivery.svg'); ?>" width="68px">
        <div class="item-title"><?php echo $this->t->_('fast_delivery'); ?></div>
        <p><?php echo $this->t->_('fast_delivery_text'); ?></p>
    </div>
    <div class="grid-33 coins">
        <img src="<?php $this->h()->static()->path('warranty/coins.svg'); ?>" width="58px">
        <div class="item-title"><?php echo $this->t->_('warranty_return'); ?></div>
        <p><?php echo $this->t->_('warranty_return_text'); ?></p>
    </div>
</div>
