<?php echo $this->render('controls/header.phtml'); ?>

<div class="grid-container">
    <div class="breadcrumbs grid-100 mobile-grid-100" itemprop="breadcrumb">
        <a href="<?= $this->h()->url()->build('/'); ?>"><?php echo $this->t->_('main_page_link'); ?></a> &raquo;
        <?php echo $this->t->_('transportation_info'); ?>
        <div class="underline"></div>
    </div>

    <div id="cooperation" class="grid-100 mobile-grid-100">
        <h1><?php echo $this->t->_('forma_dostavky'); ?>:</h1>
        <p class="sapce"><?php echo $this->t->_('forma_dostavky_text'); ?>:</p>

        <div><a href="http://www.autolux.ua/" target="_blank" class="list"><?php echo $this->t->_('avto_lyks'); ?></a></div>
        <div><a href="http://www.novaposhta.com.ua/" target="_blank" class="list sapce"><?php echo $this->t->_('new_post'); ?></a></div>

        <p><?php echo $this->t->_('area'); ?></p>
        <p class="large-sapce"><?php echo $this->t->_('bad_produces'); ?></p>

        <?php echo $this->render("controls/info/transportation-{$this->language}.phtml") ?>
    </div>
</div>

<?php echo $this->render('controls/footer.phtml'); ?>
