---
driver:
  name: localhost

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: macosx-10

suites:
- name: default
  run_list:
    - selenium_test::hub
    - selenium_test::node
  attributes:
    selenium_test:
      username: travis
      password: travis
