<?php echo $this->render('controls/header.phtml'); ?>
<div class="grid-container">
    <div class="breadcrumbs grid-100" itemprop="breadcrumb">
        <a href="<?= $this->h()->url()->build(''); ?>"><?php echo $this->t->_('main_page_link'); ?></a> &raquo;
        <?php echo $this->t->_('wl_menu'); ?>
        <?php if(!$this->wlList): ?><div class="underline"></div><?php endif; ?>
    </div>

    <div class="grid-100">
        <?php if($this->wlList && is_array($this->wlList) && count($this->wlList)):?>
            <table class="tablesorter" cellpadding="3" cellspacing="1">
                <thead>
                    <tr>
                        <th><?php echo $this->t->_('name'); ?></th>
                        <th><?php echo $this->t->_('domain'); ?></th>
                        <th width="200px" class="{sorter: false}"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php $i = 1; ?>
                    <?php foreach ($this->wlList as $key => $value): ?>
                        <td><?php echo $value['name'];?></td>
                        <td>
                            <a href="http://<?php echo $value['domain'];?>" target="_blank"><?php echo $value['domain'];?></a>
                        </td>
                        <td>
                            <a href="<?= $this->h()->url()->build("/wl/products/code/{$value['code']}"); ?>" class="violet-btn">
                                <?php echo $this->t->_('products'); ?>
                            </a>
                            <a href="<?= $this->h()->url()->build("/wl/statistic/code/{$value['code']}"); ?>" class="violet-btn">
                                <?php echo $this->t->_('orders'); ?>
                            </a>
                        </td>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <div class="grid-100 notification-msg center-allign">
                <span><?php echo $this->t->_('you_do_not_have_activated_wl_yet'); ?></span>
            </div>
        <?php endif; ?>
    </div>
</div>
<?php echo $this->render('controls/footer.phtml'); ?>
