<?php echo $this->render('controls/header.phtml'); ?>
<div class="grid-container">
    <div class="breadcrumbs grid-100" itemprop="breadcrumb">
        <a href="<?= $this->h()->url()->build(''); ?>"><?php echo $this->t->_('main_page_link'); ?></a> &raquo;
        <a href="<?= $this->h()->url()->build('/wl'); ?>"><?php echo $this->t->_('wl_menu'); ?></a> &raquo;
        <?php echo $this->wl['name']; ?>
        <div class="underline"></div>
    </div>

    <div class="grid-100">
        <div id="catalog" data-wl-code="<?php echo $this->wl['code']; ?>">
            <div class="product-categories">
                <div class="shop-product-theme selected" data-group-id="">
                    <?php echo $this->t->_('all'); ?>
                    <span class="arrow">&raquo;</span>
                </div>
                <?php foreach ($this->publicProductsGroup as $productsGroup): ?>
                    <div class="shop-product-theme" data-group-id="<?php echo $productsGroup['id']; ?>" data-group-name="<?php echo $productsGroup['name']; ?>">
                        <?php echo $this->t->_($productsGroup['name']); ?>
                        <span class="arrow">&raquo;</span>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="products-list">
                <div class="add-more">
                    <a id="create-more-product" href="<?= $this->h()->url()->build('/wl/selectproducts/code/'.$this->wl['code']); ?>" class="violet-btn">
                        <?php echo $this->t->_('add_more_product'); ?>
                    </a>
                </div>
                <div id="shop-content-products"></div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->render('controls/footer.phtml'); ?>
