<?php echo $this->render('controls/header.phtml') ?>
<?php $this->tmpSeoUrl = end($this->breadcrumbs) ?>
<?php echo $this->render('controls/breadcrumbs.phtml'); ?>

<?php if ($this->isEditSiteSettingsOn): ?>
    <style>
        form {font-size: 14px;}
        label {display: block;font-weight: bold;padding-bottom: 5px;}
        input[type=text] {padding-bottom: 5px;width: 100%;}
        textarea {width: 100%;height: 250px;}
        .copy-seo-data {list-style: none;padding-top: 5px;}
        .copy-seo-data li {cursor: pointer;}
        .copy-seo-data li:hover {color: #009900;}
        .seo-warning-msg {font-weight: bold;color: firebrick;}
        .seo-routes-list li:hover {background: #ffe6e5;}
        .arrow-block {position: relative;float: left;z-index: 3;left: 50%;display: none;}
        .grid-product:hover .arrow-block {display: block;}
        .grid-product:hover .arrow-block img {opacity: 0.5;}
        .grid-product:hover .arrow-block img:hover {opacity: 1;}
        .arrow-block > div {position: absolute;width: 96px;left: -48px;top: 78px;}
        .arrow-block img {background-color: #b900b7;border-radius: 11px;cursor: pointer;}
        .arrow-up {margin-left: 32px;}
        .arrow-left {margin-right: 16px;}
        .arrow-right {margin-left: 16px;}
        .arrow-down {margin-left: 32px;}
    </style>
    <script>
        $(document).ready(function () {
            $('.copy-seo-data li').click(function () {
                var itemId = $(this).parent('ul').data('for-field');
                if ($('#' + itemId).val() != '') {
                    var dialog = confirm("<?= $this->t->_('this_field_already_contain_data_do_you_want_to_replays_it') ?>?");
                    if (dialog !== true) {
                        return;
                    }
                }
                $('#' + itemId).val($(this).html().trim());
            });
            $(document).on('click', '.arrow-block img', function () {
                var index = $(this).parents('.grid-product').index();
                if (parseInt($(this).data('el-count')) < 0) {
                    $('#products .grid-product:eq(' + (index + $(this).data('el-count')) + ')').before(
                        $('#products .grid-product:eq(' + index + ')')
                    );
                } else {
                    $('#products .grid-product:eq(' + (index + $(this).data('el-count')) + ')').after(
                        $('#products .grid-product:eq(' + index + ')')
                    );
                }
            });
            $('#save-product-position').click(function () {
                var productIds = '';
                $('#products .grid-product').each(function () {
                    productIds += (productIds != '') ? ',' + $(this).data("product-id") : $(this).data("product-id");
                });
                $.ajax({
                    type: "POST",
                    url: baseUrl + "/admin/save-product-position",
                    data: {
                        productIds: productIds,
                        themeId: '<?= $this->currentThemeId ?>',
                        tagId: '<?= $this->currentSubThemeId ?>'
                    },
                    success: function(data) {
                        alert('<?= $this->t->_('product_order_was_saved') ?>');
                    }
                });
            });
        });
    </script>
<?php endif; ?>

<div class="page-content">
    <?php echo $this->render('controls/products/seo-content.phtml'); ?>

    <div class="grid-container">
        <div id="catalog" class="catalog" data-item="<?php echo $this->item ?>">
            <nav class="v-nav grid-25 mobile-grid-100">
                <a class="green-btn hide-on-mobile"
                   href="<?= $this->h()->url()->build("/produces/create/item/{$this->item}"); ?>">
                    <?php echo $this->t->_("create_own_{$this->group}"); ?>
                </a>

                <div class="clear"></div>
                <ul id="categories" itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement"
                    data-current="<?php echo $this->currentThemeId ?>">
                    <li class="title"><?php echo $this->t->_('all_categories') ?><span id="view-hide-group">+</span>
                    </li>
                    <?php if ($this->item == 'mantshirt'): ?>
                        <?php if ($this->currentThemeId == null): ?>
                            <li class="selected">
                                <span itemprop="name">
                                    <?php echo $this->t->_('all'); ?>
                                </span>
                            </li>
                        <?php else: ?>
                            <?php $tShirtUrlAll = ($this->language == 'ru') ? '/futbolki-muzhskie' : '/futbolky-muzhski'; ?>
                            <li>
                                <a itemprop="url" href="<?= $this->h()->url()->build($tShirtUrlAll) ?>">
                                    <span itemprop="name">
                                        <?php echo $this->t->_('all'); ?>
                                    </span>
                                </a>
                            </li>
                        <?php endif; ?>
                    <?php elseif ($this->item == 'womantshirt'): ?>
                        <?php if ($this->currentThemeId == null): ?>
                            <li class="selected">
                                <span itemprop="name">
                                    <?php echo $this->t->_('all'); ?>
                                </span>
                            </li>
                        <?php else: ?>
                            <?php $tShirtUrlAll = ($this->language == 'ru') ? '/futbolki-womantshirt-zhenskie' : '/futbolky-womantshirt-zhinochi'; ?>
                            <li>
                                <a itemprop="url" href="<?= $this->h()->url()->build($tShirtUrlAll) ?>">
                                    <span itemprop="name">
                                        <?php echo $this->t->_('all'); ?>
                                    </span>
                                </a>
                            </li>
                        <?php endif; ?>
                    <?php else: ?>
                        <?php if ($this->currentThemeId == null): ?>
                            <li class="selected">
                                <span itemprop="name">
                                    <?php echo $this->t->_('all'); ?>
                                </span>
                            </li>
                        <?php else: ?>
                            <li>
                                <a itemprop="url"
                                   href="<?= $this->h()->url()->build("/produces/catalog/item/{$this->item}") ?>">
                                    <span itemprop="name">
                                        <?php echo $this->t->_('all'); ?>
                                    </span>
                                </a>
                            </li>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php foreach ($this->productsThemes as $theme): ?>
                        <li<?php echo ($this->currentThemeId == $theme['id']) ? ' class="selected"' : ''; ?>>
                            <?php if ($this->currentThemeId == $theme['id']): ?>
                                <span itemprop="name">
                                    <?php echo $theme[$this->language] ?>
                                </span>
                            <?php else: ?>
                                <a itemprop="url" href="<?=
                                ($theme['seo_url'])
                                    ? $this->h()->url()->seo($theme['seo_url'])
                                    : $this->h()->url()->build(
                                    "/produces/catalog/item/{$this->item}",
                                    ['themeId' => $theme['id']]
                                );
                                ?>">
                                    <span itemprop="name">
                                        <?php echo $theme[$this->language] ?>
                                    </span>
                                </a>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </nav>
            <?php if ($this->id): ?>
                <div class="grid-75 mobile-grid-100 grid-parent" data-group-name="<?php echo $this->group ?>"
                     data-item-name="<?php echo $this->item ?>"
                     itemscope itemtype="http://schema.org/Product">
                    <?php echo $this->render('produces/view.phtml'); ?>
                </div>
            <?php else: ?>
                <div class="grid-75 mobile-grid-100 grid-parent" data-group-name="<?php echo $this->group ?>"
                     data-item-name="<?= $this->item ?>" itemscope itemtype="http://schema.org/ItemList">
                    <meta itemprop="itemListOrder" content="Descending"/>

                    <?php if (is_array($this->themesTags) && count($this->themesTags)): ?>
                        <div id="tags" class="grid-100 mobile-grid-100"
                             data-current="<?php echo $this->currentSubThemeId ?>">
                            <div class="sub-category-tag">
                                <?php foreach ($this->themesTags as $key => $tag): ?>
                                    <?php echo ($key != 0) ? ' | ' : ''; ?>
                                    <?php if ($this->currentSubThemeId == $tag['id']): ?>
                                        <?php echo $tag[$this->language]; ?>
                                    <?php else: ?>
                                        <?php if ($tag['seo_url']): ?>
                                            <a href="<?= $this->h()->url()->seo($tag['seo_url']) ?>"
                                               data-sub-category-id="<?php echo $tag['id'] ?>">
                                                <?php echo $tag[$this->language] ?>
                                            </a>
                                        <?php elseif ($tag['theme_seo_url']): ?>
                                            <a href="<?= $this->h()->url()->seo($tag['theme_seo_url'], array('tagId' => $tag['id'])) ?>"
                                               data-sub-category-id="<?php echo $tag['id'] ?>">
                                                <?php echo $tag[$this->language] ?>
                                            </a>
                                        <?php else: ?>
                                            <a href="<?= $this->h()->url()->build("/produces/catalog/item/{$this->item}", array('themeId' => $this->currentThemeId, 'tagId' => $tag['id'])) ?>"
                                               data-sub-category-id="<?php echo $tag['id'] ?>">
                                                <?php echo $tag[$this->language] ?>
                                            </a>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    <?php endif; ?>

                    <?php if ($this->isEditSiteSettingsOn): ?>
                        <?php if ($this->seoRouteRedirects): ?>
                            <div class="grid-100 mobile-grid-100" style="padding-top: 10px;">
                                <label><?= $this->t->_('current_redirects') ?>:</label>
                                <ul class="seo-routes-list" style="text-decoration: none; list-style-type: none;">
                                    <?php foreach ($this->seoRouteRedirects as $redirect): ?>
                                        <li style="width:100%;">
                                            <?= $redirect['url'] ?>
                                            <a href="<?= $this->h()->url()->build('/admin/delete-seo-url', ['id' => $redirect['id']]) ?>"
                                               style="float: right;">
                                                <?= $this->t->_('delete') ?>
                                            </a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        <?php endif; ?>

                        <div class="grid-100 mobile-grid-100" style="padding-top: 10px;">
                            <form method="post" action="<?= $this->h()->url()->build('/admin/save-seo-url') ?>">
                                <input type="hidden" name="id" value="<?= $this->seoRouteRecord['id'] ?>">
                                <input type="hidden" name="url" value="<?= $this->seoRouteRecord['url'] ?>">
                                <input type="hidden" name="lang" value="<?= $this->seoRouteRecord['lang'] ?>">
                                <input type="hidden" name="controller"
                                       value="<?= $this->seoRouteRecord['controller'] ?>">
                                <input type="hidden" name="action" value="<?= $this->seoRouteRecord['action'] ?>">
                                <input type="hidden" name="param1-name"
                                       value="<?= $this->seoRouteRecord['param1_name'] ?>">
                                <input type="hidden" name="param1-val"
                                       value="<?= $this->seoRouteRecord['param1_val'] ?>">
                                <input type="hidden" name="param2-name"
                                       value="<?= $this->seoRouteRecord['param2_name'] ?>">
                                <input type="hidden" name="param2-val"
                                       value="<?= $this->seoRouteRecord['param2_val'] ?>">
                                <input type="hidden" name="get1-name" value="<?= $this->seoRouteRecord['get1_name'] ?>">
                                <input type="hidden" name="get1-val" value="<?= $this->seoRouteRecord['get1_val'] ?>">
                                <input type="hidden" name="get2-name" value="<?= $this->seoRouteRecord['get2_name'] ?>">
                                <input type="hidden" name="get2-val" value="<?= $this->seoRouteRecord['get2_val'] ?>">
                                <label for="seo_url"><?= $this->t->_('current_page_url') ?>:</label>
                                <input type="text" name="seo-url" id="seo-url"
                                       value="<?= $this->seoRouteRecord['seo_url'] ?>" style="width: 100%;">
                                <ul class="copy-seo-data" data-for-field="seo-url">
                                    <li><?= $this->h()->seo()->proposeCategoryUrl($this->language, $this->item, $this->tmpSeoUrl['name']) ?></li>
                                </ul>
                                <div style="text-align: right; padding-top: 5px;">
                                    <input type="submit" value="<?= $this->t->_('save') ?>">
                                </div>
                            </form>
                        </div>
                    <?php endif; ?>

                    <div id="products" data-page-count="<?= $this->pageCount ?>">
                        <?php echo $this->render('produces/catalog-products.phtml'); ?>
                    </div>

                    <?php if ($this->isEditSiteSettingsOn): ?>
                        <div class="right" style="padding: 0 7px 10px 0;">
                            <input id="save-product-position" type="button" class="btn" value="<?= $this->t->_('save_product_position') ?>" />
                        </div>
                    <?php endif ?>

                    <?php if ($this->pageCount > 1): ?>
                        <div id="load-more" class="product-paging-bottom grid-100 mobile-grid-100">
                            <button id="load-more-product" class="green-btn grid-33 prefix-33 mobile-grid-100">
                                <?= $this->t->_('load_more') ?>
                            </button>
                        </div>
                    <?php endif ?>

                    <?php
                    $this->gaEvent = ['category' => 'Перегляд', 'action' => 'Каталог', 'label' => $this->t->_($this->item), 'value' => $this->currentThemeId];
                    echo $this->render('controls/ga/event.phtml');
                    ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#view-hide-group').bind('touchstart click', function (e) {
            e.preventDefault();
            if ($('nav.v-nav ul').hasClass('view-all')) {
                $('nav.v-nav ul').removeClass('view-all');
                $(this).text('+');
            } else {
                $('nav.v-nav ul').addClass('view-all');
                $(this).text('-');
            }
            return false;
        });
    });
</script>

<?php echo $this->render('controls/footer.phtml') ?>
