---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.0
  - name: debian-7.8
  - name: fedora-20
  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2

suites:
  - name: default
    run_list:
      - apt
      - chrome_test
      - chrome_test::x11
    attributes:
      apt:
       compile_time_update: true
