<script type="text/javascript">
    function mark(side) {
        $('.bookmark').hide();
        $('.postcard-tab-' + side).show();
    }
    $(document).ready(function(){
//        $('.postcard-tab-front .content').click(function(){
//            $('.bookmark').hide();
//            $('.inner').show();
//        });
//        $('.postcard .inner .left').click(function(){
//            $('.bookmark').hide();
//            $('.front').show();
//        });
//        $('.postcard .inner .right').click(function(){
//            $('.bookmark').hide();
//            $('.back').show();
//        });
//        $('.postcard .back .block').click(function(){
//            $('.bookmark').hide();
//            $('.inner').show();
//        });
    });
</script>

<div class="postcard">
    <div class="postcard-tab-front bookmark">
        <div class="size-origin-postcard block">
            <div class="content">
                <?php $this->h()->image()->getInBoxImg($this->itemXml, 'main'); ?>
            </div>
        </div>
        <?php if($this->showFullInfo): ?>
            <div class="side-links">
                <?php echo $this->t->_('main_page') ?> |
                <a href="javascript:mark('middle');">
                    <?php echo $this->t->_('inner_page') ?>
                </a> |
                <a href="javascript:mark('back');">
                    <?php echo $this->t->_('last_page') ?>
                </a>
            </div>
        <?php endif; ?>
    </div>
    <?php if($this->showFullInfo): ?>
        <div class="postcard-tab-middle bookmark hidden">
            <div class="pages">
                <div class="size block left">
                    <div class="content">
                        <?php $this->h()->image()->getInBoxImg($this->itemXml, 'inner'); ?>
                    </div>
                </div>
                <div class="size-origin-postcard block right">
                    <div class="content">
                        <div class="text-box-zoomed postcard-content-zoom text-block">
                            <div class="postcard-text"><?php echo $this->itemXml->content->text; ?></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="side-links">
                <a href="javascript:mark('front');">
                    <?php echo $this->t->_('main_page') ?>
                </a> |
                <?php echo $this->t->_('inner_page') ?> |
                <a href="javascript:mark('back');">
                    <?php echo $this->t->_('last_page') ?>
                </a>
            </div>
        </div>
        <div class="postcard-tab-back bookmark hidden">
            <div class="content size-origin-postcard">
                <img src="<?php echo $this->baseUrl; ?>/public/theme/produces/postcard/postcardBackSimple.png">
            </div>
            <div class="side-links">
                <a href="javascript:mark('front');">
                    <?php echo $this->t->_('main_page') ?>
                </a> |
                <a href="javascript:mark('middle');">
                    <?php echo $this->t->_('inner_page') ?>
                </a> |
                <?php echo $this->t->_('last_page') ?>
            </div>
        </div>
    <?php endif; ?>
</div>
