<?php echo $this->render('controls/emptyheader.phtml'); ?>

<div style="padding: 20px;">
    <div style="text-align:center; vertical-align:middle; width:310px; height:210px;">
        <h4><?php echo $this->t->_('themes'); ?></h4>
        <div id="scrollPanel" style="width: 100%;  height: 190px; overflow: auto;">
        <ul style="padding-top: 8px; list-style-type: none;">
            <?php foreach ($this->show_themes as $key => $value): ?>
                <li style="padding-bottom: 3px;">
                    <?php if($value['name'] != 'this_user_id'): ?>
                            <a id="theme<?php echo $value['name']; ?>" href="#" style="padding:3px;" onclick="changeTheme('<?php echo $value['name']; ?>'); return false;"><?php echo $this->t->_($value['name']); ?></a>
                    <?php else: ?>
                            <a id="theme<?php echo $value['name']; ?>" href="#" style="padding:3px;" onclick="changeTheme('<?php echo $this->current_user_id; ?>'); return false;"><?php echo $this->t->_($value['name']); ?></a>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#scrollPanel").jScrollPane({ showArrows: true });
</script>
<?php echo $this->render('controls/emptyfooter.phtml'); ?>