<?php echo $this->render('controls/header.phtml'); ?>
<?php echo $this->render('controls/breadcrumbs.phtml'); ?>

<div class="page-content">
    <?php if (($this->t->_('header') != 'header' && $this->t->_('header') != '') || ($this->t->_('content') != 'content' && $this->t->_('content') != '')): ?>
        <div class="text-block">
            <div class="grid-container">
                <div class="underline"></div>
                <div class="grid-100 mobile-grid-100"><?php
                    if ($this->t->_('header') != 'header'):
                        ?><h1 class="header"><?= $this->t->_('header'); ?></h1><?php
                    endif;
                    if ($this->t->_('header') != 'header'):
                        ?><div class="text-four-column"><?php echo $this->t->_('content'); ?></div><?php
                    endif;
                ?></div>
            </div>
        </div>
    <?php endif; ?>
    <div class="grid-container">
        <nav class="grid-25 mobile-grid-100 v-nav" itemscope itemtype="http://schema.org/SiteNavigationElement">
            <ul>
                <li class="title"><?php echo $this->t->_('we_propose', $this->supportLanguage) . ':'; ?><span id="view-hide-group">+</span></li>
                <?php foreach ($this->publicProductsGroup as $key => $value): ?>
                    <?php if ($this->group != $value['name']): ?>
                        <li>
                            <a itemprop="url" href="<?= $this->h()->url()->build("/produces/products/group/{$value['name']}"); ?>">
                                <span itemprop="name">
                                    <?php echo $this->t->_($value['name'], $this->supportLanguage); ?>
                                </span>
                            </a>
                        </li>
                    <?php else: ?>
                        <li class="selected">
                            <span>
                                <?php echo $this->t->_($this->group, $this->supportLanguage); ?>
                            </span>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </nav>

        <div id="products" class="products grid-75 mobile-grid-100">
            <?php foreach ($this->publicProductsDatails as $key => $product): ?>
                <?php if ($key != 0): ?> <div class="underline"></div> <?php endif; ?>
                <div class="info">
                    <h2><?php echo $this->t->_($product['name']); ?></h2>
                    <div class="image">
                        <img class="no-border preview-product-images" alt="<?php echo $this->t->_("{$product['name']}_alt"); ?>" data-product-item="<?= $product['name'] ?>"
                             src="<?php $this->h()->static()->path("produces/tovlist/{$this->group}/{$product['name']}/1_small.jpg") ?>" width="200" height="150">
                        <span class="zoom linker preview-product-images hide-on-mobile " data-product-item="<?= $product['name'] ?>">
                            <img class="no-border" src="<?php $this->h()->static()->path('produces/zoomImg.png') ?>" width="24" height="24"
                                 alt="<?= $this->t->_('zoom'); ?>"><span><?= $this->t->_('zoom'); ?></span>
                        </span>
                    </div>

                    <div class="details">
                        <?php if ($this->t->_('param1' . '_' . $product['name']) != 'param1' . '_' . $product['name']): ?>
                            <div>
                                <label><?php echo $this->t->_('param1'); ?>:</label>
                                <span><?php echo $this->t->_('param1' . '_' . $product['name']); ?></span>
                            </div>
                        <?php endif;
                        if ($this->t->_('param2' . '_' . $product['name']) != 'param2' . '_' . $product['name']): ?>
                            <div>
                                <label><?php echo $this->t->_('param2'); ?>:</label>
                                <span><?php echo $this->t->_('param2' . '_' . $product['name']); ?></span>
                            </div>
                        <?php endif;
                        if ($this->t->_('param3' . '_' . $product['name']) != 'param3' . '_' . $product['name']): ?>
                            <div>
                                <label><?php echo $this->t->_('param3'); ?>:</label>
                                <span><?php echo $this->t->_('param3' . '_' . $product['name']); ?></span>
                            </div>
                        <?php endif;
                        if ($this->t->_('param4' . '_' . $product['name']) != 'param4' . '_' . $product['name']): ?>
                            <div>
                                <label><?php echo $this->t->_('param4'); ?>:</label>
                                <span><?php echo $this->t->_('param4' . '_' . $product['name']); ?></span>
                            </div>
                        <?php endif; ?>
                        <div>
                            <label><?php echo $this->t->_('price'); ?>:</label>
                            <span class="price"><?php echo $product['price'] . ' ' . $this->t->_('grn'); ?>.</span>
                        </div>
                        <div class="functional">
                            <a class="violet-btn" href="<?= ($product['seo_url']) ? $this->h()->url()->seo($product['seo_url']) : $this->h()->url()->build("/produces/catalog/item/{$product['name']}") ?>">
                                &raquo; <?php echo $this->t->_('catalog', $this->supportLanguage); ?>
                            </a>
                            <a class="green-btn hide-on-mobile" href="<?= $this->h()->url()->build("/produces/create/item/{$product['name']}"); ?>">
                                &raquo; <?php echo $this->t->_("create_own_{$this->group}", $this->supportLanguage); ?>
                            </a>
                        </div>
                    </div>

                </div>
                <div class="clear"></div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<?php echo $this->render('controls/footer.phtml'); ?>
