<style>
    .h-nav {
        margin-bottom: 10px;;
    }
</style>

<ul class="h-nav">
    <li class="balance">
        <a href="<?= $this->h()->url()->build("/partnership?type=balance"); ?>"><?php
            echo $this->t->_("balance") ?>(<?php echo $this->benefit . ' ' . $this->t->_("grn")
        ?>)</a>
    </li>
    <li class="ref">
        <a href="<?= $this->h()->url()->build("/partnership?type=ref"); ?>"><?php echo $this->t->_("referrals") ?></a>
    </li>
    <li class="public">
        <a href="<?= $this->h()->url()->build("/partnership?type=public"); ?>"><?php echo $this->t->_("public_shop") ?></a>
    </li>
    <!--div id="basket-status">
        <a href="<?= $this->h()->url()->build("/partnership?type=balance"); ?>" class="green-btn">
            <?php echo $this->t->_("balance") ?>: .
        </a>
    </div-->
</ul>
