---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: <%= ENV["machine_port"] %>
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: windows-2012R2

suites:
- name: default
  run_list:
    - recipe[java_se]
    - recipe[selenium_grid::hub]
    - recipe[selenium_grid::node]
  attributes:
    selenium_grid:
      username: <%= ENV["machine_user"] %>
      password: <%= ENV["machine_pass"] %>
      display:
        width: 1280
        height: 1024
      chrome:
        max_instances: 5
      firefox:
        max_instances: 5
      htmlunit:
        max_instances: 1
      ie:
        max_instances: 1
