# Usage: KITCHEN_YAML=.kitchen.docker.yml bundle exec kitchen list
---
driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false

platforms:
- name: centos-6
  driver:
    image: centos:6
    intermediate_instructions:
      - RUN yum -y install tar which initscripts gcc libffi-devel

- name: centos-7
  driver:
    image: centos:7
    intermediate_instructions:
      - RUN yum clean all
      - RUN yum -y install net-tools lsof gcc libffi-devel
    pid_one_command: /usr/lib/systemd/systemd

- name: debian-7
  driver:
    image: debian:7
    intermediate_instructions:
      - RUN /usr/bin/apt-get update && /usr/bin/apt-get upgrade -y
      - RUN /usr/bin/apt-get install apt-transport-https net-tools gcc libffi-dev -y

- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools gcc libffi-dev -y

- name: fedora-latest
  driver:
    image: fedora:latest
    intermediate_instructions:
    - RUN yum clean all
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install tar yum gcc libffi-devel

- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools gcc libffi-dev -y

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools gcc libffi-dev -y

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools gcc libffi-dev -y

suites:
- name: default
  run_list:
    - recipe[java_se]
    - recipe[selenium_grid::hub]
    - recipe[selenium_grid::node]
  attributes:
    selenium_grid:
      username: travis
      password: travis
      display:
        width: 1280
        height: 1024
      chrome:
        max_instances: 5
      firefox:
        max_instances: 5
      htmlunit:
        max_instances: 1
      ie:
        max_instances: 1
