<?php echo $this->render('controls/emptyheader.phtml'); ?>

<script>
    var wallPostMessage = '<?php echo $this->t->_('wall_post_message')?>';
    var wallImagePostTitle = '<?php echo $this->t->_('wall_image_post_title')?>';
    var wallImagePostMessage = '<?php echo $this->t->_('wall_image_post_message')?>';
</script>
<style>
    #partners-ref{
        overflow: auto;
    }
    #partners-ref .info{
        float:left;
        width: 500px;
        padding: 20px;
    }
    #partners-ref .info h2{
        text-align: center;
        padding-bottom: 5px;
    }
    .sett_label {
        color: #4F575B;
        display: block;
        font-size: 14px;
        font-weight: bold;
        padding-bottom: 3px;
    }
    .sett_input {
        border-color: #7F9FB5 #ADC7DA #ADC7DA !important;
        border-image: none !important;
        border-radius: 2px 2px 2px 2px !important;
        border-right: 1px solid #ADC7DA !important;
        border-style: solid !important;
        border-width: 1px !important;
        color: #2E3335 !important;
        padding: 7px 5px !important;
        width: 100% !important;
    }
    #partners-ref .btns{
        float: right;
        width: 340px;
        padding: 20px;
    }
    .services_conn_list {
        list-style:none;
        font-family: arial,helvetica,tahoma,verdana,sans-serif;
    }
    .services_conn_list li {
        margin: 15px 0;
    }
    .services_conn_list li a {
        display: block;
        width: 100%;
        background-color: #c8e5f3;
        border: 1px solid #afd3e4;
        padding: 10px 8px 10px 36px;
        font-size: 14px;
        font-weight: bold;
        border-radius: 2px;
    }
    .services_conn_list li a:hover {
        text-decoration: none;
        background-color: #D6F2B8 !important;
        border: 1px solid #BCD886 !important;
        color: #4C710B;
    }
    .conn_vk a {
        background: url(../public/theme/social/vk.png) no-repeat 5px 6px;
    }
    .conn_fb a {
        background: url(../public/theme/social/fb.png) no-repeat 5px 6px;
    }
    .conn_tw a {
        background: url(../public/theme/social/tweet.png) no-repeat 5px 6px;
    }
</style>
<?php if($this->acceptShopRules): ?>
    <?php echo $this->render('partnership/controls/shopstatus.phtml'); ?>
<div id="partners-ref" class="grid-100">
    <div class="info">
        <h2><?php echo $this->t->_('ref_title'); ?></h2>
        <?php echo $this->t->_('ref_text'); ?>
    </div>
    <div class="btns">
        <ul class="services_conn_list">
            <li>
                <label class="sett_label" id="full_name_label"><?php echo $this->t->_('url'); ?></label>
                <input type="text" value="http://<?php echo $_SERVER['HTTP_HOST'].$this->baseUrl.'?refKey='.$this->refKey; ?>"
                       class="sett_input" name="full-url-ref" id="full-url-ref" data-url-ref-code="<?php echo $this->refKey; ?>">
            </li>
            <li class="conn_vk">
                <a id="post-to-vk" style="cursor: pointer;"><?php echo $this->t->_('share_in_vk'); ?></a>
            </li>
            <li class="conn_fb">
                <a id="post-to-fb" style="cursor: pointer;"><?php echo $this->t->_('share_in_facebook'); ?></a>
                <div id="fb-root" style="display: none;"></div>
            </li>
            <!--li class="conn_tw">
                <a style="cursor: pointer;"><?php echo $this->t->_('share_in_twitter'); ?></a>
            </li-->
        </ul>
    </div>
</div>
<script type="text/javascript" src="http://userapi.com/js/api/openapi.js"></script>
<script type="text/javascript" src="http://connect.facebook.net/en_US/all.js"></script>
<?php else: ?>
    <?php echo $this->t->_('you_dont_accept_rules_yet'); ?>
<?php endif; ?>
<?php echo $this->render('controls/emptyfooter.phtml'); ?>
