<?php if($this->isEditSiteSettingsOn): ?>
    <div class="grid-100 mobile-grid-100">
        <form method="post" action="<?= $this->h()->url()->build('/admin/save-seo-url') ?>">
            <input type="hidden" name="id" value="<?= $this->seoRouteRecord['id'] ?>">
            <input type="hidden" name="url" value="<?= $this->seoRouteRecord['url'] ?>">
            <input type="hidden" name="lang" value="<?= $this->seoRouteRecord['lang'] ?>">
            <input type="hidden" name="controller" value="<?= $this->seoRouteRecord['controller'] ?>">
            <input type="hidden" name="action" value="<?= $this->seoRouteRecord['action'] ?>">
            <input type="hidden" name="param1-name" value="<?= $this->seoRouteRecord['param1_name'] ?>">
            <input type="hidden" name="param1-val" value="<?= $this->seoRouteRecord['param1_val'] ?>">
            <input type="hidden" name="param2-name" value="<?= $this->seoRouteRecord['param2_name'] ?>">
            <input type="hidden" name="param2-val" value="<?= $this->seoRouteRecord['param2_val'] ?>">
            <input type="hidden" name="get1-name" value="<?= $this->seoRouteRecord['get1_name'] ?>">
            <input type="hidden" name="get1-val" value="<?= $this->seoRouteRecord['get1_val'] ?>">
            <input type="hidden" name="get2-name" value="<?= $this->seoRouteRecord['get2_name'] ?>">
            <input type="hidden" name="get2-val" value="<?= $this->seoRouteRecord['get2_val'] ?>">
            <label for="seo_url"><?= $this->t->_('current_page_url') ?>:</label>
            <input type="text" name="seo-url" id="seo-url" value="<?= $this->seoRouteRecord['seo_url'] ?>" style="width: 100%;">
            <ul class="copy-seo-data" data-for-field="seo-url">
                <li><?= $this->h()->seo()->proposeCategoryUrl($this->language,  'one_' . $this->item, $this->tmpSeoUrl['name']) ?></li>
            </ul>
            <div style="text-align: right; padding-top: 5px;">
                <input type="submit" value="<?= $this->t->_('save') ?>">
            </div>
        </form>
    </div>
<?php endif; ?>
<?php $currentColor = null; ?>
<h1 itemprop="name" class="grid-100 mobile-grid-100">
    <?php if ($this->t->_('header') != 'header' && $this->t->_('header') != '') : ?>
        <?php echo $this->t->_('header'); ?>
    <?php elseif ($this->product["header_{$this->language}"]): ?>
        <?php echo $this->product["header_{$this->language}"]; ?>
    <?php elseif ($this->product[$this->language]): ?>
        <?php echo $this->product[$this->language]; ?>
    <?php endif; ?>
</h1>
<div class="view grid-65 mobile-grid-100">
    <?= $this->h()->product()->getImg($this->t, $this->item, $this->product, 'o') ?>
</div>
<div class="details grid-35 mobile-grid-100">
    <div class="owner hide-on-mobile">
        <div class="name">
            <div>
                <label><?php echo $this->t->_('author') ?>:</label>&nbsp;
                <span><?php echo $this->userInfo->user_name; ?></span>
            </div>
            <div>
                <label><?php echo $this->t->_('created_products') ?>:</label>&nbsp;
                <b><?php echo $this->userProductsCount; ?></b>
            </div>
        </div>
        <img id="avatar-img"
            src="<?php $this->h()->image()->avatar($this->userInfo->name, 'p', $this->userInfo->extension) ?>"
            alt="<?php echo $this->userInfo->user_name; ?>" />
    </div>
    <div>
        <?php if ($this->group == 'tshirt'): ?>
            <div id="tshirt-sizes">
                <label class="new-label"><?php echo $this->t->_('size') ?>:</label>
                <span>S</span>
                <span>M</span>
                <span>L</span>
                <span>XL</span>
                <span>XXL</span>
            </div>
            <div>
                <span class="t-shirt-sizes-grid linker" data-product-item="<?= $this->item ?>">
                    <?php echo $this->t->_('t_shirt_sizes') ?>
                </span>
            </div>

            <?php if ($this->colors && is_array($this->colors) && count($this->colors)): ?>
                <div id="tshirt-color">
                    <label class="new-label"><?php echo $this->t->_('color') ?>:</label>
                    <?php foreach ($this->colors as $color): ?>
                        <?php if(!$this->product['allowed_colors'] || strpos($this->product['allowed_colors'], $color) !== false): ?>
                            <?php $selected = ($color == $this->product['color']) ? ' selected' : ''; ?>
                            <span class="<?= $color . $selected; ?>" data-color="<?= $color ?>"
                                data-img="<?= $this->h()->product()->getImgUrl($this->item, $this->product, 'front', 'o', $color); ?>"></span>
                            <?php if ($color == $this->product['color']): $currentColor = $color; endif ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        <?php endif; ?>

        <?php if (($this->product["description_{$this->language}"]) || ($this->t->_('content') != 'content' && $this->t->_('content') != '')): ?>
            <div class="description">
                <label class="new-label"><?php echo $this->t->_('description_msg') ?>:</label>
                <div itemprop="description">
                    <?php if ($this->t->_('content') != 'content' && $this->t->_('content') != ''): ?>
                        <?php echo $this->t->_('content'); ?>
                    <?php else: ?>
                        <?php echo $this->product["description_{$this->language}"]; ?>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>

        <div class="view-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
            <label class="new-label">
                <?php echo $this->t->_('price') ?>:
            </label>&nbsp;
            <span itemprop="price">
                <?php echo $this->h()->basket()->showPrice($this->product, $this->item); ?>
            </span>
            <?php echo ' ' . $this->t->_('grn') ?>.
            <meta itemprop="priceCurrency" content="UAH" />
            <link itemprop="availability" href="http://schema.org/InStock" />
        </div>
        <div class="functional">
            <?php if ($this->group == 'postcard'): ?>
                <a class="green-btn" href="<?= $this->h()->url()->build("/produces/create/item/{$this->item}", array('upid' => $this->id)); ?>">
                    <?php echo $this->t->_('buy'); ?>
                </a>
            <?php else: ?>
                <form id="add-to-basket" method="post" action="<?= $this->h()->url()->build('/user/add-basket-item'); ?>">
                    <input type="hidden" id="product-id" name="product-id" value="<?php echo $this->id; ?>">
                    <input type="hidden" id="item" name="item" value="<?php echo $this->item; ?>">
                    <input type="hidden" id="size" name="size" value="">
                    <input type="hidden" id="color" name="color" value="">
                    <input type="submit" value="<?php echo $this->t->_('add_to_basket'); ?>"
                        class="ga-event-tracking add-to-basket" data-ga-category="Корзина" data-ga-action="Добавити"
                        data-ga-label="<?php echo $this->t->_($this->item); ?>" data-ga-value="<?php echo $this->id; ?>">
                </form>
            <?php endif; ?>
        </div>
        <div class="share-buttons">
            <?php $urlEncoded = urlencode(str_replace('my/p', 'photoprint.in.ua', $this->requestFullUri)) ?>

            <a href="http://www.facebook.com/sharer.php?p[url]=<?= $urlEncoded ?>" class="fb"
               onclick="javascript:window.open(this.href,'','menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
               target="_blank" title="Share on Facebook">

            <!--/a><a href="https://pinterest.com/pin/create/bookmarklet/?media=<?= $urlImg ?>&url=<?= $urlEncoded ?>&is_video=false&description=<?= $urlDescription ?>" class="p"
               onclick="javascript:window.open(this.href,'','menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
               target="_blank" title="Share on Pinterest">

            </a><a href="http://twitter.com/share?text=encodeURIComponent(ptitle)&url=<?= $urlEncoded ?>&counturl=<?= $urlEncoded ?>" class="t"
               onclick="javascript:window.open(this.href,'','menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
               target="_blank" title="Share on Twitter"-->

            </a><a href="http://vkontakte.ru/share.php?url=<?= $urlEncoded ?>" class="vk"
               onclick="javascript:window.open(this.href,'','menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
               target="_blank" title="Share on Vkontakte">

            <!--/a><a href="https://plus.google.com/share?url=<?= $urlEncoded ?>" class="g"
               onclick="javascript:window.open(this.href,'','menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=350,width=480');return false;"
               target="_blank" title="Share on Google+"-->
            </a>
        </div>
    </div>
    <?php $this->viewedItem = $this->item; ?>
</div>
<div class="clear"></div>

<div class="grid-100 mobile-grid-100">
    <ul class="h-nav">
        <li class="selected" data-content-el="similar">
            <?= $this->t->_('similar_products') ?>
        </li>
        <li class="ga-event-tracking" data-content-el="warranty" data-ga-category="" data-ga-action="" data-ga-label="" data-ga-value="">
            <?= $this->t->_('our_warranties') ?>
        </li>
    </ul>
</div>

<div id="similar-product" class="similar-product">
    <div class="message grid-100 mobile-grid-100">
        <?php echo $this->t->_('other_products_from_same_category'); ?>
        <div class="underline-dot"></div>
    </div>
    <?php foreach ($this->similarProducts as $product): ?>
        <?php $this->productName = $product[$this->language]; ?>

        <div class="grid-product" itemprop="isSimilarTo" itemscope itemtype="http://schema.org/Product">
            <div class="preview">
                <div class="image" style="text-align: center;">
                    <?= $this->h()->product()->getImg($this->t, $product['item'], $product, 'p'); ?>
                </div>
                <div class="info-more">
                    <?php
                    $productUrl = (isset($product['seo_url']) && !empty($product['seo_url']))
                        ? $this->h()->url()->seo($product['seo_url'])
                        : $this->h()->url()->build("/produces/catalog/item/{$product['item']}", array('id' => $product['id']))
                    ?>
                    <a itemprop="name" class="view-item" href="<?= $productUrl ?>">
                        <span itemprop="name">
                            <?= (($this->productName == '') ? $this->t->_('deteils') : $this->productName); ?>
                        </span>
                    </a>
                </div>
                <div class="info" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                    <link itemprop="availability" href="http://schema.org/InStock"/>
                    <meta itemprop="priceCurrency" content="UAH"/>
                    <span itemprop="price">
                        <?= $this->h()->basket()->showPrice($product['content_xml'], $product['item']); ?>
                    </span>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
<div id="transportation-and-paympnd-product" class="grid-100 similar-product"></div>

<?php
$this->gaEvent = ['category' => 'Перегляд', 'action' => 'Продукт', 'label' => $this->t->_($this->viewedItem), 'value' => $this->id];
echo $this->render('controls/ga/event.phtml');
?>
