<?php echo $this->render('controls/header.phtml'); ?>

<style>
.elPrice input[type=text] {
    padding: 0;
    width: 110px;
}
</style>
<div class="grid-container">
    <div class="grid-100">
    <table class="tablesorter" cellpadding="3" cellspacing="1">
        <thead>
            <tr>
                <th><?php echo $this->t->_('name'); ?></th>
                <th><?php echo $this->t->_('tov_type_name'); ?></th>
                <th width="150px;"><?php echo $this->t->_('price'); ?></th>
                <th width="80px;"><?php echo $this->t->_('published'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php $i = 1; ?>
        <?php $hasNewOrder = false; ?>
        <?php foreach ($this->productsPrice as $key => $value): ?>
            <tr align="center">
                <td valign="middle"><?php echo $this->t->_($value['group_name']); ?></td>
                <td valign="middle"><?php echo $this->t->_($value['name'].$value['template_id']); ?></td>
                <td valign="middle">
                    <div class="elPrice" data-item-id="<?php echo $value['id']; ?>" data-template-id="<?php echo $value['template_id']; ?>" style="width:120px; float:left; text-align:right;"><?php echo $value['price']; ?></div>
                    <div class="price" style="float:right;">
                        <img class="editBtn" style="cursor:pointer;" src="<?php echo $this->baseUrl?>/public/theme/user/table/edit.png" />
                        <img class="saveBtn" style="display: none; cursor:pointer; padding-top: 3px;" src="<?php echo $this->baseUrl?>/public/theme/user/table/save.png" />
                    </div>
                </td>
                <td valign="middle">
                    <?php if(!$value['template_id']): ?>
                    <div class="elPublished" data-item-id="<?php echo $value['id']; ?>" style="width:60px; float:left; text-align:right;"><?php echo $value['published']; ?></div>
                    <div class="published" style="float:right;">
                        <img class="editBtn" style="cursor:pointer;" src="<?php echo $this->baseUrl?>/public/theme/user/table/edit.png" />
                        <img class="saveBtn" style="display: none; cursor:pointer; padding-top: 3px;" src="<?php echo $this->baseUrl?>/public/theme/user/table/save.png" />
                    </div>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    </div>
</div>

<?php echo $this->render('controls/footer.phtml'); ?>
