<script language="javascript" type="text/javascript">
     var tov_wos_added = '<?php echo $this->t->_('tov_was_added'); ?>';
     var tov_wos_updated = '<?php echo $this->t->_('tov_wos_updated'); ?>';
     var select_photo_first = '<?php echo $this->t->_('select_photo_first'); ?>';
     var select_size_first = '<?php echo $this->t->_('select_size_first'); ?>';
     var ok_btn = '<?php echo $this->t->_('ok_btn'); ?>';
     var cancel_btn = '<?php echo $this->t->_('cancel_btn'); ?>';
</script>
<table class="studio-funcional-btn" cellpadding="0" cellspacing="0">
    <tr>
        <td colspan="2">
            <?php if(!$this->itemId): ?>
                <img class="basketbtn" src="<?php echo $this->baseUrl; ?>/public/theme/produces/basketbtn.png">
            <?php else: ?>
                <img class="basketbtn" src="<?php echo $this->baseUrl; ?>/public/theme/produces/savebasketbtn.png">
            <?php endif; ?>
        </td>
    </tr>
    <tr>
        <td>
            <img class="rotateleft180btn" src="<?php echo $this->baseUrl; ?>/public/theme/produces/rotateleft180btn.png">
        </td>
        <td>
            <img class="rotateright180btn" src="<?php echo $this->baseUrl; ?>/public/theme/produces/rotateright180btn.png">
        </td>
    </tr>
    <tr>
        <td>
            <img class="rotateright90btn" src="<?php echo $this->baseUrl; ?>/public/theme/produces/rotateright90btn.png">
        </td>
        <td>
            <img class="rotateleft90btn" src="<?php echo $this->baseUrl; ?>/public/theme/produces/rotateleft90btn.png">
        </td>
    </tr>
    <tr>
        <td>
            <img class="fullbtn" src="<?php echo $this->baseUrl; ?>/public/theme/produces/fullsizebtn.png">
        </td>
        <td>
            <img class="centerbtn" src="<?php echo $this->baseUrl; ?>/public/theme/produces/realsizebtn.png">
        </td>
    </tr>
    <tr>
        <td>
            <img class="plasbtn" src="<?php echo $this->baseUrl; ?>/public/theme/produces/zoomplasbtn.png">
        </td>
        <td>
            <img class="minusbtn" src="<?php echo $this->baseUrl; ?>/public/theme/produces/zoomminesbtn.png">
        </td>
    </tr>
    <tr>
        <td>
            <img class="rightbtn" src="<?php echo $this->baseUrl; ?>/public/theme/produces/leftbtn.png">
        </td>
        <td>
            <img class="leftbtn" src="<?php echo $this->baseUrl; ?>/public/theme/produces/rightbtn.png">
        </td>
    </tr>
    <tr>
        <td>
            <img class="downbtn" src="<?php echo $this->baseUrl; ?>/public/theme/produces/downbtn.png">
        </td>
        <td>
            <img class="upbtn" src="<?php echo $this->baseUrl; ?>/public/theme/produces/upbtn.png">
        </td>
    </tr>
</table>