<?php echo $this->render('controls/header.phtml'); ?>

<div id="help-page" class="grid-container">
    <div class="breadcrumbs grid-100 mobile-grid-100" itemprop="breadcrumb">
        <a href="<?= $this->h()->url()->build(''); ?>"><?php echo $this->t->_('main_page_link'); ?></a> &raquo;
        <?php echo $this->t->_('business'); ?>
        <div class="underline"></div>
    </div>

    <?php echo $this->render("controls/info/business-{$this->language}.phtml") ?>
</div>

<?php echo $this->render('controls/footer.phtml'); ?>
