<?php echo $this->render('controls/header.phtml'); ?>

<div id="help-page" class="grid-container">
    <div class="breadcrumbs grid-100 mobile-grid-100" itemprop="breadcrumb">
        <a href="<?= $this->h()->url()->build(''); ?>"><?php echo $this->t->_('main_page_link'); ?></a> &raquo;
        <?php echo $this->t->_('help_info'); ?>
        <div class="underline"></div>
    </div>

    <div id="warranty-product" class="grid-100 mobile-grid-100">
        <h1>
            <?php echo $this->t->_('warranty_promo_msg'); ?>
        </h1>
        <h2>
            &raquo; <?php echo $this->t->_('our_warranty'); ?>
        </h2>
        <div class="grid-33 alpha quality">
            <img src="<?php $this->h()->static()->path('warranty/quality.svg'); ?>" width="50px">
            <div class="item-title"><?php echo $this->t->_('warranty_quality'); ?></div>
            <p><?php echo $this->t->_('warranty_quality_text'); ?></p>
        </div>
        <div class="grid-33 delivery">
            <img src="<?php $this->h()->static()->path('warranty/delivery.svg'); ?>" width="68px">
            <div class="item-title"><?php echo $this->t->_('fast_delivery'); ?></div>
            <p><?php echo $this->t->_('fast_delivery_text'); ?></p>
        </div>
        <div class="grid-33 omega coins">
            <img src="<?php $this->h()->static()->path('warranty/coins.svg'); ?>" width="58px">
            <div class="item-title"><?php echo $this->t->_('warranty_return'); ?></div>
            <p><?php echo $this->t->_('warranty_return_text'); ?></p>
        </div>
    </div>

    <?php echo $this->render("controls/info/help-{$this->language}.phtml") ?>
</div>

<?php echo $this->render('controls/footer.phtml'); ?>
