<?php echo $this->render('controls/header.phtml'); ?>

<div class="grid-container">
    <div class="breadcrumbs grid-100 mobile-grid-100" itemprop="breadcrumb">
        <a href="<?= $this->h()->url()->build(''); ?>"><?php echo $this->t->_('main_page_link'); ?></a> &raquo;
        <?php echo $this->t->_('payment_info'); ?>
        <div class="underline"></div>
    </div>

    <div id="cooperation" class="grid-100 mobile-grid-100">
        <h1><?php echo $this->t->_('forma_oplaty'); ?>:</h1>

        <p class="sapce"><?= $this->t->_('payment_types_you_can_use') ?>: </p>
        <p class="list">
            <a href="http://www.webmoney.ru/" target="_blank" class="web-money">WebMoney</a>
            <span class="web-money-img">
                <a href="http://www.megastock.ru/" target="_blank">
                    <img src="http://www.megastock.ru/Doc/88x31_accept/purple_rus.gif" alt="www.megastock.ru" border="0">
                </a>
            </span>
            <span class="web-money-passport">
                <a href="https://passport.webmoney.ru/asp/certview.asp?wmid=421106455114" target="_blank">
                    <img class="no-border" src="http://www.megastock.ru/Doc/88x31_merchant/purple_rus.gif" alt="Здесь находится аттестат нашего WM идентификатора 421106455114" border="0" />
                    <span><?= $this->t->_('check_passport') ?></span>
                </a>
            </span>
        </p>
        <p class="list"><?php echo $this->t->_('after_receive'); ?></p>

        <?php echo $this->render("controls/info/payment-{$this->language}.phtml") ?>
    </div>
</div>

<?php echo $this->render('controls/footer.phtml'); ?>
