<?php if(!is_array($this->pageBaseUrlParams)): $this->pageBaseUrlParams = array(); endif;
if ($this->pageCount > 1):
    if ($this->currentPage > 1):
        ?><a class="paging" data-page-number="1" href="<?= $this->h()->url()->build($this->pageBaseUrl, $this->pageBaseUrlParams) ?>">|<</a>&nbsp;&nbsp;&nbsp;<?php
        $prefPageParam = (($this->currentPage - 1) == 1) ? $this->pageBaseUrlParams : array_merge($this->pageBaseUrlParams, array('page' => $this->currentPage - 1));
        ?><a class="paging" data-page-number="<?php echo $this->currentPage - 1; ?>" href="<?= $this->h()->url()->build($this->pageBaseUrl, $prefPageParam) ?>"><<</a><?php
    endif;

    echo ($this->currentPage - 3 > 1) ? '&nbsp;&nbsp;&nbsp;...&nbsp;&nbsp;&nbsp;' : '&nbsp;&nbsp;&nbsp;';

    for ($i = $this->currentPage - 3; $i < $this->currentPage + 4; $i++):
        if (($i > 0) && ($i < ($this->pageCount + 1))) :
            if ($i != $this->currentPage):
                $currentPageParam = ($i == 1) ? $this->pageBaseUrlParams : array_merge($this->pageBaseUrlParams, array('page' => $i))
                ?><a class="paging" data-page-number="<?php echo $i; ?>" href="<?= $this->h()->url()->build($this->pageBaseUrl, $currentPageParam) ?>"><?php echo $i; ?></a>&nbsp;&nbsp;&nbsp;<?php
            else:
                echo $i.'&nbsp;&nbsp;&nbsp;';
            endif;
        endif;
    endfor;

    echo (($this->currentPage + 4) < ($this->pageCount + 1)) ? '...&nbsp;&nbsp;&nbsp;' : '&nbsp;';

    if ($this->currentPage < $this->pageCount):
        ?><a class="paging" data-page-number="<?php echo $this->currentPage + 1; ?>" href="<?= $this->h()->url()->build($this->pageBaseUrl, array_merge($this->pageBaseUrlParams, array('page' => $this->currentPage + 1))) ?>">>></a>&nbsp;&nbsp;&nbsp;<?php
        ?><a class="paging" data-page-number="<?php echo $this->pageCount; ?>" href="<?= $this->h()->url()->build($this->pageBaseUrl, array_merge($this->pageBaseUrlParams, array('page' => $this->pageCount))) ?>">>|</a><?php
    endif;
endif; ?>
