<div id="popup-wnd-data-content" class="popup-wnd-partner-select-product-size">
    <?php echo $this->render('controls/emptyheader.phtml'); ?>

    <div style="text-align: center;">
        <div class="popup-wnd-header"><?php echo $this->t->_('select_products'); ?></div>
        
        <?php foreach ($this->publicProductsGroup as $productGroup): ?>
            <div style="padding-bottom: 5px;">
                <a href="<?= $this->h()->url()->build("/wl/create/group/{$productGroup['name']}/code/{$this->wlCode}"); ?>">
                    <?php echo $this->t->_($productGroup['name']); ?>
                </a>
            </div>
        <?php endforeach; ?>
    </div>

    <?php echo $this->render('controls/emptyfooter.phtml'); ?>
</div>