<?php echo $this->render('header.phtml'); ?>
    <tr>
        <td style="padding: 10px; border-bottom: 1px solid #f2eeed;">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td style="padding: 0 0 15px 0; font-size: 20px; line-height: 28px; font-weight: bold;">
                        <?= $this->t->_('congratulation_your_account_is_created') ?>
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 16px; line-height: 22px;">
                        <?= $this->t->_('your_registration_data') ?>:
                        <br /><br />
                        <?= $this->t->_('login') ?>: <?= $this->email ?>
                        <br />
                        <?= $this->t->_('password') ?>: <?= $this->password ?>
                        <br /><br />
                        <?= sprintf($this->t->_('to_confirm_you_email_go_to'), $this->email) ?>
                        <a href="<?= $this->h()->url()->buildFullUrl('/user/confirmation', ['hash' => $this->hash]) ?>">
                            <?= $this->t->_('confirm_email') ?>
                        </a>
                        <br /><br />
                    </td>
                </tr>
            </table>
        </td>
    </tr>
<?php echo $this->render('footer.phtml'); ?>
