<?php echo $this->render('header.phtml'); ?>
    <tr>
        <td style="padding: 10px; border-bottom: 1px solid #f2eeed;">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td style="padding: 0 0 15px 0; font-size: 20px; line-height: 28px; font-weight: bold;">
                        <?= $this->t->_('password_recovery') ?>
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 16px; line-height: 22px;">
                        <?= sprintf($this->t->_('hello'), $this->userName) ?>
                        <br><br>
                        <?= $this->t->_('why_you_receive_a_letter') ?>
                        <br><br>
                        <?= $this->t->_('open_link') ?>
                        <br>
                        <a href="<?= $this->h()->url()->buildFullUrl('/user/reset-password', ['hash' => $this->hash]); ?>" target="_blank">
                            <?= $this->h()->url()->buildFullUrl('/user/reset-password', ['hash' => $this->hash]); ?>
                        </a>
                        <br>
                        <br>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
<?php echo $this->render('footer.phtml'); ?>
