<style>
    #payout-history{
        float:left;
        padding-top: 5px;
    }
    #balance-general {
        text-align: right;
        font: 15px bold;
        font-family: arial,helvetica,tahoma,verdana,sans-serif;
        padding: 20px 0px 20px 0px;
    }
    #balance-general label{
        display: inline-block;
        width: 120px;
        text-align: left;
        padding-left: 2px;;
    }
    #balance-general span{
        display: inline-block;
        width: 100px;
        text-align: right;
    }
</style>

<?php echo $this->render('partnership/controls/shopstatus.phtml'); ?>
<div class="menu-underline"></div>

<div id="payout-history">
    <?php if($this->payOutHistory): ?>
        <div>
            <?php echo $this->t->_('history'); ?>
        </div>
        <?php foreach($this->payOutHistory as $key => $value): ?>
            <div>
                <?php echo date('d/m/Y H:m', strtotime($value['created'])); ?> -
                <?php echo $value['sum'] . ' ' . $this->t->_('grn') ?>.
                (<?php echo $this->t->_($value['status']); ?>)
            </div>
        <?php endforeach; ?>
    <?php endif;; ?>
</div>
<div id="balance-general">
    <div>
        <div>
            <label class="closed"><?php echo $this->t->_('total'); ?>:</label><span class="closed"><?php echo $this->productsGrouped['benefitDone'] . ' ' . $this->t->_('grn'); ?>.</span>
        </div>
        <div>
            <label class="pending"><?php echo $this->t->_('in_process'); ?>:</label><span class="pending"><?php echo $this->productsGrouped['benefitInProcess'] . ' ' . $this->t->_('grn'); ?>.</span>
        </div>
        <div>
            <label class="canceled"><?php echo $this->t->_('canceled_orders'); ?>:</label><span class="canceled"><?php echo $this->productsGrouped['benefitCanceled'] . ' ' . $this->t->_('grn'); ?>.</span>
        </div>
        <div style="padding-top: 5px; text-align: right;">
            <?php if($this->productsGrouped['benefitDone'] >= UsersPayOut::$minSum): ?>
                <a class="mbox green-btn" href="<?= $this->h()->url()->build('/partnership/payoutwnd')?>"><?php echo $this->t->_('pay_me'); ?></a>
            <?php else: ?>
                *<?php echo $this->t->_('min_sum_for_payout_is'); ?> <b><?php echo UsersPayOut::$minSum; ?></b> <?php echo $this->t->_('grn'); ?>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php if($this->productsGrouped['data'] && count($this->productsGrouped['data']) > 0): ?>
    <h2 style="text-align: center; padding: 10px;">
        <?php echo $this->t->_('balance_details'); ?>
    </h2>
    <div>
        <table class="tablesorter" cellpadding="3" cellspacing="1">
            <thead>
            <tr>
                <th><?php echo $this->t->_('orders'); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->productsGrouped['data'] as $value): ?>
                <tr>
                    <td>
                        <div>
                            <label><?php echo $this->t->_('orderet'); ?>:</label>
                            <?php echo $value['ordered']; ?>
                        </div>
                        <div>
                            <label><?php echo $this->t->_('totalbenefit'); ?>:</label>
                            <?php echo $value['totalbenefit']; ?>  <?php echo $this->t->_('grn'); ?>
                        </div>
                        <div>
                            <label><?php echo $this->t->_('status'); ?>:</label>
                            <?php echo $this->t->_($value['status']); ?>
                        </div>


                        <table class="tablesorter" cellpadding="3" cellspacing="1">
                            <thead>
                            <tr>
                                <th><?php echo $this->t->_('item'); ?></th>
                                <th style="width: 60px;"><?php echo $this->t->_('count'); ?></th>
                                <th style="width: 60px;"><?php echo $this->t->_('total'); ?></th>
                                <th style="width: 60px;"><?php echo $this->t->_('byref'); ?></th>
                                <th style="width: 80px;"><?php echo $this->t->_('byprod'); ?></th>
                                <th style="width: 60px;"><?php echo $this->t->_('mybenefit'); ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($value['items'] as $item): ?>
                                <?php if($value['status'] == 'closed'): ?><tr class="closed">
                                <?php elseif($value['status'] == 'canceled'): ?><tr class="canceled">
                                <?php else: ?><tr class="pending">
                                <?php endif; ?>
                                    <td>
                                        <?php echo $this->t->_($item['item']); ?>
                                    </td>
                                    <td>
                                        <?php echo $item['count']; ?>
                                    </td>
                                    <td>
                                        <?php echo $item['price'] . ' ' . $this->t->_('grn')?>
                                    </td>
                                    <td>
                                        <?php echo $item['byref']; ?>
                                    </td>
                                    <td>
                                        <?php echo $item['byprod']; ?>
                                    </td>
                                    <td>
                                        <?php echo $item['itembenefit'] . ' ' . $this->t->_('grn'); ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>

                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <h2 style="text-align: center; padding: 10px;">
        <?php echo $this->t->_('by_your_referrals_there_is_no_orders_yet'); ?>
    </h2>
<?php endif; ?>