<?php echo $this->render('controls/header.phtml'); ?>

<div class="grid-container">
    <div class="grid-70">
        <?php $orderSum = 0; ?>
        <?php $orderItemCount = 0; ?>
        <?php if (count($this->basketItems) > 0): ?>
            <?php foreach ($this->basketItems as $key => $basketItem): ?>
                <?php $prodPrice = $this->h()->basket()->showPrice($basketItem); ?>
                <div class="basket-item" data-basket-item-id="<?php echo $basketItem['id']; ?>">
                    <div class="image">
                        <?php $dataXml = new SimpleXMLElement(stripslashes($basketItem['dataXml'])); ?>
                        <?php $item = (string) $dataXml->item; ?>
                        <?= $this->h()->product()->getImg($this->t, $item, $basketItem, 'i'); ?>
                    </div>
                    <div class="info">
                        <div class="title-block">
                            <span class="title">
                                <?php echo $this->t->_($basketItem['previewModel']); ?>
                            </span>
                            <span class="item-total-price">
                                <?php echo $this->t->_('sum'); ?>:
                                <span>
                                    <?php echo number_format($basketItem['count'] * $prodPrice, 2); ?>
                                </span>
                            </span>
                            <?php $orderSum += $basketItem['count'] * $prodPrice; ?>
                        </div>
                        <a class="mbox" href="<?= $this->h()->url()->build("/user/delete-basket-item-wnd/id/{$basketItem['id']}"); ?>">
                            <img class="remove-basket-item" src="<?php $this->h()->static()->path('garbage.png'); ?>" />
                        </a>
                        <?php
                            $xmlData = new SimpleXMLElement(stripslashes($basketItem['dataXml']));
                            $color = (string) $xmlData->color;
                            $size = (string) $xmlData->size;
                        ?>
                        <?php if($size): ?>
                            <div class="info-msg">
                                <label><?php echo $this->t->_('size'); ?>:</label><?php echo $size; ?>
                            </div>
                            <div class="info-msg">
                                <label class="float"><?php echo $this->t->_('color'); ?>:</label>
                                <span class="<?php echo $color; ?> basket-tshirt-color"></span>
                            </div>
                        <?php endif; ?>
                        <div class="info-msg">
                            <label><?php echo $this->t->_('price_per_item'); ?>:</label>
                            <span class="price-per-item"><?php echo $prodPrice ?></span>
                            <?php echo ' ' . $this->t->_('grn');?>
                        </div>
                        <div class="info-msg">
                            <label class="float"><?php echo $this->t->_('quantity'); ?>:</label>
                            <span class="qty-btngroup">
                                <button class="decrease-count" type="button">-</button>
                                <input type="text" value="<?php echo $basketItem['count']; ?>" class="current-count">
                                <button class="increase-count" type="button">+</button>
                            </span>
                        </div>
                        <?php $orderItemCount += $basketItem['count']; ?>
                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            <div class="notification-msg">
                <span><?php echo $this->t->_('no_item_in_busket'); ?></span>
            </div>
        <?php endif; ?>
    </div>
    <div class="grid-30">
        <div class="order-preview">
            <div class="title">
                <?php echo $this->t->_('order_info'); ?>
            </div>
            <div class="info">
                <div class="block">
                    <label><?php echo $this->t->_('total_item_amount');?>:</label>
                    <span id="total-count">
                        <?php echo $orderItemCount; ?>
                    </span>
                </div>
                <div class="block">
                    <label><?php echo $this->t->_('total_order_price');?>:</label>
                    <span id="total-amount">
                        <?php echo number_format($orderSum, 2); ?>
                    </span>
                </div>
            </div>
            <div class="functional">
                <button type="button" id="create-order-btn" class="green-btn">
                    <?php echo $this->t->_('make_order'); ?>
                </button>
            </div>
        </div>
    </div>
</div>

<?php
$this->gaEvent = ['category' => 'Перегляд', 'action' => 'Корзина'];
echo $this->render('controls/ga/event.phtml');
?>

<?php echo $this->render('controls/footer.phtml'); ?>
