<?php if(!$this->item): ?>
    <?php $this->item = ($this->itemXml != '' && $this->itemXml->item != '') ? $this->itemXml->item : 'cork'; ?>
<?php endif; ?>

<?php $borderClass = (in_array($this->item, array('cork', 'square', 'rubber'))) ? 'square' : 'circle'; ?>
<?php $imgAlt = $this->t->_($this->item) . '. ' . $this->productName; ?>

<div class="trivet">
    <div class="content size">
        <span class="border size <?php echo $borderClass; ?>"></span>
        <?php $this->h()->image()->getSmallInBoxImgPreview(1.44937, $this->itemXml, 'main', $imgAlt, 0, 0) ?>
    </div>
</div>
